In [1]:
pip install faker

Requirement already satisfied: faker in c:\users\admin\anaconda3\lib\site-packages (35.2.0)
Requirement already satisfied: python-dateutil>=2.4 in c:\users\admin\anaconda3\lib\site-packages (from faker) (2.9.0.post0)
Requirement already satisfied: typing-extensions in c:\users\admin\anaconda3\lib\site-packages (from faker) (4.11.0)
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\lib\site-packages (from python-dateutil>=2.4->faker) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
#pip install faker --no-warn-script-location

In [3]:
import random

In [4]:
import faker

In [5]:
import pandas as pd

In [6]:
fake = faker.Faker()

data = {
    "First Name": ["Aarav", "Isha", "Poonam", "Zoya", "Anil", "Gayatri", "Yuvraj", "Krish", "Dimple", "Rahul"],
    "Last Name": ["Sharma", "Roy", "Lohar", "Shah", "Karaniya", "Auti", "Lohar", "Lohar", "Roy", "Lohar"],
    "Email ID": [fake.email() for _ in range(10)],
    "Age": [random.randint(18,35) for _ in range(10)]
}

data

{'First Name': ['Aarav',
  'Isha',
  'Poonam',
  'Zoya',
  'Anil',
  'Gayatri',
  'Yuvraj',
  'Krish',
  'Dimple',
  'Rahul'],
 'Last Name': ['Sharma',
  'Roy',
  'Lohar',
  'Shah',
  'Karaniya',
  'Auti',
  'Lohar',
  'Lohar',
  'Roy',
  'Lohar'],
 'Email ID': ['mollywood@example.com',
  'philip24@example.org',
  'allenashley@example.com',
  'sanchezwilliam@example.com',
  'nglenn@example.org',
  'coxcynthia@example.org',
  'susan42@example.com',
  'clarktami@example.org',
  'mcguireshelby@example.net',
  'donaldbrown@example.net'],
 'Age': [26, 21, 20, 27, 20, 30, 27, 35, 18, 28]}

In [7]:
pd.DataFrame(data)

  First Name Last Name                    Email ID  Age
0      Aarav    Sharma       mollywood@example.com   26
1       Isha       Roy        philip24@example.org   21
2     Poonam     Lohar     allenashley@example.com   20
3       Zoya      Shah  sanchezwilliam@example.com   27
4       Anil  Karaniya          nglenn@example.org   20
5    Gayatri      Auti      coxcynthia@example.org   30
6     Yuvraj     Lohar         susan42@example.com   27
7      Krish     Lohar       clarktami@example.org   35
8     Dimple       Roy   mcguireshelby@example.net   18
9      Rahul     Lohar     donaldbrown@example.net   28

In [8]:
print(fake.name())

Juan Ward

In [9]:
print(fake.address())

76867 Hammond Pine
Youngport, OK 39582

In [10]:
print(fake.phone_number())

+1-643-883-1973x96090

In [11]:
data = []
for _ in range(10):
    record = {
        "Name" : fake.name(),
        "Address" : fake.address(),
        "Email" : fake.email(),
        "Date of Birth" : fake.date_of_birth(),
        "Phone Number" : fake.phone_number(),
        "Company" : fake.company()
    }
    data.append(record)

In [12]:
data

[{'Name': 'Francisco Harris',
  'Address': '91291 James Glen\nGabrielport, FM 50440',
  'Email': 'nbuckley@example.org',
  'Date of Birth': datetime.date(1910, 7, 3),
  'Phone Number': '(349)835-7258x549',
  'Company': 'Rios LLC'},
 {'Name': 'Danielle Jackson',
  'Address': '649 Rivera Forges Suite 276\nNorth David, WY 66061',
  'Email': 'mlopez@example.net',
  'Date of Birth': datetime.date(1962, 10, 23),
  'Phone Number': '(385)788-2317',
  'Company': 'Jones, Hall and Rosales'},
 {'Name': 'Robin Anderson',
  'Address': '4681 Melody Lodge Suite 396\nNorth Barbara, NM 03874',
  'Email': 'cmcgrath@example.org',
  'Date of Birth': datetime.date(1922, 11, 27),
  'Phone Number': '+1-582-905-9376x624',
  'Company': 'Brown LLC'},
 {'Name': 'William Roy',
  'Address': '5458 Douglas Knolls\nEast Danielle, HI 37347',
  'Email': 'npeters@example.org',
  'Date of Birth': datetime.date(1998, 10, 2),
  'Phone Number': '457.778.0809',
  'Company': 'Hodges-Williams'},
 {'Name': 'Gregory Osborne',
  'Address': '705 Michelle Knoll\nLake Cassandrabury, MP 65153',
  'Email': 'edwardskathleen@example.com',
  'Date of Birth': datetime.date(1982, 6, 5),
  'Phone Number': '337-692-0704x499',
  'Company': 'Krueger-Gallegos'},
 {'Name': 'Lance Roberts',
  'Address': '983 Curtis Row Suite 197\nSouth Jeromeburgh, MT 53536',
  'Email': 'amcmahon@example.net',
  'Date of Birth': datetime.date(2004, 5, 4),
  'Phone Number': '+1-596-318-7368x45361',
  'Company': 'Choi, Green and Suarez'},
 {'Name': 'Victoria Franklin',
  'Address': '9724 Rojas Dale Suite 692\nColemanfurt, AZ 77092',
  'Email': 'john85@example.net',
  'Date of Birth': datetime.date(1993, 3, 6),
  'Phone Number': '+1-553-626-2362x04119',
  'Company': 'Diaz Group'},
 {'Name': 'Charles Mack',
  'Address': '210 Phillips Club Suite 212\nAndrewville, NH 23243',
  'Email': 'kellyandrade@example.org',
  'Date of Birth': datetime.date(1911, 5, 19),
  'Phone Number': '766-962-8163x29485',
  'Company': 'Stephens LLC'},
 {'Name': 'Catherine Miller',
  'Address': '55231 James Throughway\nJessicaberg, AL 84754',
  'Email': 'yramos@example.net',
  'Date of Birth': datetime.date(2008, 10, 8),
  'Phone Number': '484.531.5089',
  'Company': 'Adams, Holt and Martinez'},
 {'Name': 'Michael Wright',
  'Address': '47989 Robinson Meadow\nLake Brendamouth, KS 56993',
  'Email': 'charlesbullock@example.net',
  'Date of Birth': datetime.date(1935, 7, 1),
  'Phone Number': '768-818-7370x27158',
  'Company': 'Thomas, Lee and Johnson'}]

In [13]:
df = pd.DataFrame(data)

In [14]:
df

,Name,Address,Email,Date of Birth,Phone Number,Company
0,Francisco Harris,"91291 James Glen\nGabrielport, FM 50440",nbuckley@example.org,1910-07-03,(349)835-7258x549,Rios LLC
1,Danielle Jackson,"649 Rivera Forges Suite 276\nNorth David, WY 6...",mlopez@example.net,1962-10-23,(385)788-2317,"Jones, Hall and Rosales"
2,Robin Anderson,"4681 Melody Lodge Suite 396\nNorth Barbara, NM...",cmcgrath@example.org,1922-11-27,+1-582-905-9376x624,Brown LLC
3,William Roy,"5458 Douglas Knolls\nEast Danielle, HI 37347",npeters@example.org,1998-10-02,457.778.0809,Hodges-Williams
4,Gregory Osborne,"705 Michelle Knoll\nLake Cassandrabury, MP 65153",edwardskathleen@example.com,1982-06-05,337-692-0704x499,Krueger-Gallegos
5,Lance Roberts,"983 Curtis Row Suite 197\nSouth Jeromeburgh, M...",amcmahon@example.net,2004-05-04,+1-596-318-7368x45361,"Choi, Green and Suarez"
6,Victoria Franklin,"9724 Rojas Dale Suite 692\nColemanfurt, AZ 77092",john85@example.net,1993-03-06,+1-553-626-2362x04119,Diaz Group
7,Charles Mack,"210 Phillips Club Suite 212\nAndrewville, NH 2...",kellyandrade@example.org,1911-05-19,766-962-8163x29485,Stephens LLC
8,Catherine Miller,"55231 James Throughway\nJessicaberg, AL 84754",yramos@example.net,2008-10-08,484.531.5089,"Adams, Holt and Martinez"
9,Michael Wright,"47989 Robinson Meadow\nLake Brendamouth, KS 56993",charlesbullock@example.net,1935-07-01,768-818-7370x27158,"Thomas, Lee and Johnson"

In [15]:
fake= faker.Faker('en_IN')

In [16]:
print(fake.name())

Lucky Kashyap

In [17]:
df.columns

Index(['Name', 'Address', 'Email', 'Date of Birth', 'Phone Number', 'Company'], dtype='object')

In [18]:
df.rename(columns={df.columns[0]:"Full Name"}, inplace=True)
df

,Full Name,Address,Email,Date of Birth,Phone Number,Company
0,Francisco Harris,"91291 James Glen\nGabrielport, FM 50440",nbuckley@example.org,1910-07-03,(349)835-7258x549,Rios LLC
1,Danielle Jackson,"649 Rivera Forges Suite 276\nNorth David, WY 6...",mlopez@example.net,1962-10-23,(385)788-2317,"Jones, Hall and Rosales"
2,Robin Anderson,"4681 Melody Lodge Suite 396\nNorth Barbara, NM...",cmcgrath@example.org,1922-11-27,+1-582-905-9376x624,Brown LLC
3,William Roy,"5458 Douglas Knolls\nEast Danielle, HI 37347",npeters@example.org,1998-10-02,457.778.0809,Hodges-Williams
4,Gregory Osborne,"705 Michelle Knoll\nLake Cassandrabury, MP 65153",edwardskathleen@example.com,1982-06-05,337-692-0704x499,Krueger-Gallegos
5,Lance Roberts,"983 Curtis Row Suite 197\nSouth Jeromeburgh, M...",amcmahon@example.net,2004-05-04,+1-596-318-7368x45361,"Choi, Green and Suarez"
6,Victoria Franklin,"9724 Rojas Dale Suite 692\nColemanfurt, AZ 77092",john85@example.net,1993-03-06,+1-553-626-2362x04119,Diaz Group
7,Charles Mack,"210 Phillips Club Suite 212\nAndrewville, NH 2...",kellyandrade@example.org,1911-05-19,766-962-8163x29485,Stephens LLC
8,Catherine Miller,"55231 James Throughway\nJessicaberg, AL 84754",yramos@example.net,2008-10-08,484.531.5089,"Adams, Holt and Martinez"
9,Michael Wright,"47989 Robinson Meadow\nLake Brendamouth, KS 56993",charlesbullock@example.net,1935-07-01,768-818-7370x27158,"Thomas, Lee and Johnson"

In [19]:
df.rename(columns={
    "Phone Number": "Contact Number",
    "Email": "Email Address"
}, inplace=True)

In [20]:
df

,Full Name,Address,Email Address,Date of Birth,Contact Number,Company
0,Francisco Harris,"91291 James Glen\nGabrielport, FM 50440",nbuckley@example.org,1910-07-03,(349)835-7258x549,Rios LLC
1,Danielle Jackson,"649 Rivera Forges Suite 276\nNorth David, WY 6...",mlopez@example.net,1962-10-23,(385)788-2317,"Jones, Hall and Rosales"
2,Robin Anderson,"4681 Melody Lodge Suite 396\nNorth Barbara, NM...",cmcgrath@example.org,1922-11-27,+1-582-905-9376x624,Brown LLC
3,William Roy,"5458 Douglas Knolls\nEast Danielle, HI 37347",npeters@example.org,1998-10-02,457.778.0809,Hodges-Williams
4,Gregory Osborne,"705 Michelle Knoll\nLake Cassandrabury, MP 65153",edwardskathleen@example.com,1982-06-05,337-692-0704x499,Krueger-Gallegos
5,Lance Roberts,"983 Curtis Row Suite 197\nSouth Jeromeburgh, M...",amcmahon@example.net,2004-05-04,+1-596-318-7368x45361,"Choi, Green and Suarez"
6,Victoria Franklin,"9724 Rojas Dale Suite 692\nColemanfurt, AZ 77092",john85@example.net,1993-03-06,+1-553-626-2362x04119,Diaz Group
7,Charles Mack,"210 Phillips Club Suite 212\nAndrewville, NH 2...",kellyandrade@example.org,1911-05-19,766-962-8163x29485,Stephens LLC
8,Catherine Miller,"55231 James Throughway\nJessicaberg, AL 84754",yramos@example.net,2008-10-08,484.531.5089,"Adams, Holt and Martinez"
9,Michael Wright,"47989 Robinson Meadow\nLake Brendamouth, KS 56993",charlesbullock@example.net,1935-07-01,768-818-7370x27158,"Thomas, Lee and Johnson"

In [21]:
[x.upper() for x in df.columns]

['FULL NAME',
 'ADDRESS',
 'EMAIL ADDRESS',
 'DATE OF BIRTH',
 'CONTACT NUMBER',
 'COMPANY']

In [22]:
[x.lower() for x in df.columns]

['full name',
 'address',
 'email address',
 'date of birth',
 'contact number',
 'company']

In [23]:
df

,Full Name,Address,Email Address,Date of Birth,Contact Number,Company
0,Francisco Harris,"91291 James Glen\nGabrielport, FM 50440",nbuckley@example.org,1910-07-03,(349)835-7258x549,Rios LLC
1,Danielle Jackson,"649 Rivera Forges Suite 276\nNorth David, WY 6...",mlopez@example.net,1962-10-23,(385)788-2317,"Jones, Hall and Rosales"
2,Robin Anderson,"4681 Melody Lodge Suite 396\nNorth Barbara, NM...",cmcgrath@example.org,1922-11-27,+1-582-905-9376x624,Brown LLC
3,William Roy,"5458 Douglas Knolls\nEast Danielle, HI 37347",npeters@example.org,1998-10-02,457.778.0809,Hodges-Williams
4,Gregory Osborne,"705 Michelle Knoll\nLake Cassandrabury, MP 65153",edwardskathleen@example.com,1982-06-05,337-692-0704x499,Krueger-Gallegos
5,Lance Roberts,"983 Curtis Row Suite 197\nSouth Jeromeburgh, M...",amcmahon@example.net,2004-05-04,+1-596-318-7368x45361,"Choi, Green and Suarez"
6,Victoria Franklin,"9724 Rojas Dale Suite 692\nColemanfurt, AZ 77092",john85@example.net,1993-03-06,+1-553-626-2362x04119,Diaz Group
7,Charles Mack,"210 Phillips Club Suite 212\nAndrewville, NH 2...",kellyandrade@example.org,1911-05-19,766-962-8163x29485,Stephens LLC
8,Catherine Miller,"55231 James Throughway\nJessicaberg, AL 84754",yramos@example.net,2008-10-08,484.531.5089,"Adams, Holt and Martinez"
9,Michael Wright,"47989 Robinson Meadow\nLake Brendamouth, KS 56993",charlesbullock@example.net,1935-07-01,768-818-7370x27158,"Thomas, Lee and Johnson"

In [24]:
df.columns.str.replace(" ","_")

Index(['Full_Name', 'Address', 'Email_Address', 'Date_of_Birth',
       'Contact_Number', 'Company'],
      dtype='object')

In [25]:
df

,Full Name,Address,Email Address,Date of Birth,Contact Number,Company
0,Francisco Harris,"91291 James Glen\nGabrielport, FM 50440",nbuckley@example.org,1910-07-03,(349)835-7258x549,Rios LLC
1,Danielle Jackson,"649 Rivera Forges Suite 276\nNorth David, WY 6...",mlopez@example.net,1962-10-23,(385)788-2317,"Jones, Hall and Rosales"
2,Robin Anderson,"4681 Melody Lodge Suite 396\nNorth Barbara, NM...",cmcgrath@example.org,1922-11-27,+1-582-905-9376x624,Brown LLC
3,William Roy,"5458 Douglas Knolls\nEast Danielle, HI 37347",npeters@example.org,1998-10-02,457.778.0809,Hodges-Williams
4,Gregory Osborne,"705 Michelle Knoll\nLake Cassandrabury, MP 65153",edwardskathleen@example.com,1982-06-05,337-692-0704x499,Krueger-Gallegos
5,Lance Roberts,"983 Curtis Row Suite 197\nSouth Jeromeburgh, M...",amcmahon@example.net,2004-05-04,+1-596-318-7368x45361,"Choi, Green and Suarez"
6,Victoria Franklin,"9724 Rojas Dale Suite 692\nColemanfurt, AZ 77092",john85@example.net,1993-03-06,+1-553-626-2362x04119,Diaz Group
7,Charles Mack,"210 Phillips Club Suite 212\nAndrewville, NH 2...",kellyandrade@example.org,1911-05-19,766-962-8163x29485,Stephens LLC
8,Catherine Miller,"55231 James Throughway\nJessicaberg, AL 84754",yramos@example.net,2008-10-08,484.531.5089,"Adams, Holt and Martinez"
9,Michael Wright,"47989 Robinson Meadow\nLake Brendamouth, KS 56993",charlesbullock@example.net,1935-07-01,768-818-7370x27158,"Thomas, Lee and Johnson"

In [26]:
df.loc[2] = ['Poonam', 'Mumbai', 'poonamlohar@gmail.com', '2004-02-26', '+9197463253822', 'Microsoft']

In [27]:
df

,Full Name,Address,Email Address,Date of Birth,Contact Number,Company
0,Francisco Harris,"91291 James Glen\nGabrielport, FM 50440",nbuckley@example.org,1910-07-03,(349)835-7258x549,Rios LLC
1,Danielle Jackson,"649 Rivera Forges Suite 276\nNorth David, WY 6...",mlopez@example.net,1962-10-23,(385)788-2317,"Jones, Hall and Rosales"
2,Poonam,Mumbai,poonamlohar@gmail.com,2004-02-26,+9197463253822,Microsoft
3,William Roy,"5458 Douglas Knolls\nEast Danielle, HI 37347",npeters@example.org,1998-10-02,457.778.0809,Hodges-Williams
4,Gregory Osborne,"705 Michelle Knoll\nLake Cassandrabury, MP 65153",edwardskathleen@example.com,1982-06-05,337-692-0704x499,Krueger-Gallegos
5,Lance Roberts,"983 Curtis Row Suite 197\nSouth Jeromeburgh, M...",amcmahon@example.net,2004-05-04,+1-596-318-7368x45361,"Choi, Green and Suarez"
6,Victoria Franklin,"9724 Rojas Dale Suite 692\nColemanfurt, AZ 77092",john85@example.net,1993-03-06,+1-553-626-2362x04119,Diaz Group
7,Charles Mack,"210 Phillips Club Suite 212\nAndrewville, NH 2...",kellyandrade@example.org,1911-05-19,766-962-8163x29485,Stephens LLC
8,Catherine Miller,"55231 James Throughway\nJessicaberg, AL 84754",yramos@example.net,2008-10-08,484.531.5089,"Adams, Holt and Martinez"
9,Michael Wright,"47989 Robinson Meadow\nLake Brendamouth, KS 56993",charlesbullock@example.net,1935-07-01,768-818-7370x27158,"Thomas, Lee and Johnson"

In [28]:
df.loc[2,["Address"]]=["New Mumbai"]

In [29]:
df

,Full Name,Address,Email Address,Date of Birth,Contact Number,Company
0,Francisco Harris,"91291 James Glen\nGabrielport, FM 50440",nbuckley@example.org,1910-07-03,(349)835-7258x549,Rios LLC
1,Danielle Jackson,"649 Rivera Forges Suite 276\nNorth David, WY 6...",mlopez@example.net,1962-10-23,(385)788-2317,"Jones, Hall and Rosales"
2,Poonam,New Mumbai,poonamlohar@gmail.com,2004-02-26,+9197463253822,Microsoft
3,William Roy,"5458 Douglas Knolls\nEast Danielle, HI 37347",npeters@example.org,1998-10-02,457.778.0809,Hodges-Williams
4,Gregory Osborne,"705 Michelle Knoll\nLake Cassandrabury, MP 65153",edwardskathleen@example.com,1982-06-05,337-692-0704x499,Krueger-Gallegos
5,Lance Roberts,"983 Curtis Row Suite 197\nSouth Jeromeburgh, M...",amcmahon@example.net,2004-05-04,+1-596-318-7368x45361,"Choi, Green and Suarez"
6,Victoria Franklin,"9724 Rojas Dale Suite 692\nColemanfurt, AZ 77092",john85@example.net,1993-03-06,+1-553-626-2362x04119,Diaz Group
7,Charles Mack,"210 Phillips Club Suite 212\nAndrewville, NH 2...",kellyandrade@example.org,1911-05-19,766-962-8163x29485,Stephens LLC
8,Catherine Miller,"55231 James Throughway\nJessicaberg, AL 84754",yramos@example.net,2008-10-08,484.531.5089,"Adams, Holt and Martinez"
9,Michael Wright,"47989 Robinson Meadow\nLake Brendamouth, KS 56993",charlesbullock@example.net,1935-07-01,768-818-7370x27158,"Thomas, Lee and Johnson"

In [30]:
df["Address"].apply(len)

0    38
1    49
2    10
3    43
4    47
5    52
6    47
7    49
8    44
9    48
Name: Address, dtype: int64

In [31]:
df.apply(len)

Full Name         10
Address           10
Email Address     10
Date of Birth     10
Contact Number    10
Company           10
dtype: int64

In [32]:
len(df["Address"])

10

In [33]:
df.apply(len, axis="columns")

0    6
1    6
2    6
3    6
4    6
5    6
6    6
7    6
8    6
9    6
dtype: int64

In [34]:
def update_email(email):
    return email.upper()

In [36]:
df['Email Address'].apply(update_email)

0           NBUCKLEY@EXAMPLE.ORG
1             MLOPEZ@EXAMPLE.NET
2          POONAMLOHAR@GMAIL.COM
3            NPETERS@EXAMPLE.ORG
4    EDWARDSKATHLEEN@EXAMPLE.COM
5           AMCMAHON@EXAMPLE.NET
6             JOHN85@EXAMPLE.NET
7       KELLYANDRADE@EXAMPLE.ORG
8             YRAMOS@EXAMPLE.NET
9     CHARLESBULLOCK@EXAMPLE.NET
Name: Email Address, dtype: object

In [37]:
df

,Full Name,Address,Email Address,Date of Birth,Contact Number,Company
0,Francisco Harris,"91291 James Glen\nGabrielport, FM 50440",nbuckley@example.org,1910-07-03,(349)835-7258x549,Rios LLC
1,Danielle Jackson,"649 Rivera Forges Suite 276\nNorth David, WY 6...",mlopez@example.net,1962-10-23,(385)788-2317,"Jones, Hall and Rosales"
2,Poonam,New Mumbai,poonamlohar@gmail.com,2004-02-26,+9197463253822,Microsoft
3,William Roy,"5458 Douglas Knolls\nEast Danielle, HI 37347",npeters@example.org,1998-10-02,457.778.0809,Hodges-Williams
4,Gregory Osborne,"705 Michelle Knoll\nLake Cassandrabury, MP 65153",edwardskathleen@example.com,1982-06-05,337-692-0704x499,Krueger-Gallegos
5,Lance Roberts,"983 Curtis Row Suite 197\nSouth Jeromeburgh, M...",amcmahon@example.net,2004-05-04,+1-596-318-7368x45361,"Choi, Green and Suarez"
6,Victoria Franklin,"9724 Rojas Dale Suite 692\nColemanfurt, AZ 77092",john85@example.net,1993-03-06,+1-553-626-2362x04119,Diaz Group
7,Charles Mack,"210 Phillips Club Suite 212\nAndrewville, NH 2...",kellyandrade@example.org,1911-05-19,766-962-8163x29485,Stephens LLC
8,Catherine Miller,"55231 James Throughway\nJessicaberg, AL 84754",yramos@example.net,2008-10-08,484.531.5089,"Adams, Holt and Martinez"
9,Michael Wright,"47989 Robinson Meadow\nLake Brendamouth, KS 56993",charlesbullock@example.net,1935-07-01,768-818-7370x27158,"Thomas, Lee and Johnson"

In [38]:
df["Email Address"]= df["Email Address"].str.upper()

In [39]:
df

,Full Name,Address,Email Address,Date of Birth,Contact Number,Company
0,Francisco Harris,"91291 James Glen\nGabrielport, FM 50440",NBUCKLEY@EXAMPLE.ORG,1910-07-03,(349)835-7258x549,Rios LLC
1,Danielle Jackson,"649 Rivera Forges Suite 276\nNorth David, WY 6...",MLOPEZ@EXAMPLE.NET,1962-10-23,(385)788-2317,"Jones, Hall and Rosales"
2,Poonam,New Mumbai,POONAMLOHAR@GMAIL.COM,2004-02-26,+9197463253822,Microsoft
3,William Roy,"5458 Douglas Knolls\nEast Danielle, HI 37347",NPETERS@EXAMPLE.ORG,1998-10-02,457.778.0809,Hodges-Williams
4,Gregory Osborne,"705 Michelle Knoll\nLake Cassandrabury, MP 65153",EDWARDSKATHLEEN@EXAMPLE.COM,1982-06-05,337-692-0704x499,Krueger-Gallegos
5,Lance Roberts,"983 Curtis Row Suite 197\nSouth Jeromeburgh, M...",AMCMAHON@EXAMPLE.NET,2004-05-04,+1-596-318-7368x45361,"Choi, Green and Suarez"
6,Victoria Franklin,"9724 Rojas Dale Suite 692\nColemanfurt, AZ 77092",JOHN85@EXAMPLE.NET,1993-03-06,+1-553-626-2362x04119,Diaz Group
7,Charles Mack,"210 Phillips Club Suite 212\nAndrewville, NH 2...",KELLYANDRADE@EXAMPLE.ORG,1911-05-19,766-962-8163x29485,Stephens LLC
8,Catherine Miller,"55231 James Throughway\nJessicaberg, AL 84754",YRAMOS@EXAMPLE.NET,2008-10-08,484.531.5089,"Adams, Holt and Martinez"
9,Michael Wright,"47989 Robinson Meadow\nLake Brendamouth, KS 56993",CHARLESBULLOCK@EXAMPLE.NET,1935-07-01,768-818-7370x27158,"Thomas, Lee and Johnson"

In [40]:
df[["Full Name","Company"]].applymap(len)

C:\Users\Admin\AppData\Local\Temp\ipykernel_16448\1483338795.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[["Full Name","Company"]].applymap(len)

   Full Name  Company
0         16        8
1         16       23
2          6        9
3         11       15
4         15       16
5         13       22
6         17       10
7         12       12
8         16       24
9         14       23

In [41]:
df["Full Name"]+' '+ df["Email Address"]

0          Francisco Harris NBUCKLEY@EXAMPLE.ORG
1            Danielle Jackson MLOPEZ@EXAMPLE.NET
2                   Poonam POONAMLOHAR@GMAIL.COM
3                William Roy NPETERS@EXAMPLE.ORG
4    Gregory Osborne EDWARDSKATHLEEN@EXAMPLE.COM
5             Lance Roberts AMCMAHON@EXAMPLE.NET
6           Victoria Franklin JOHN85@EXAMPLE.NET
7          Charles Mack KELLYANDRADE@EXAMPLE.ORG
8            Catherine Miller YRAMOS@EXAMPLE.NET
9      Michael Wright CHARLESBULLOCK@EXAMPLE.NET
dtype: object

In [42]:
df["Details"]= df["Full Name"]+' '+ df["Email Address"]

In [43]:
df

,Full Name,Address,Email Address,Date of Birth,Contact Number,Company,Details
0,Francisco Harris,"91291 James Glen\nGabrielport, FM 50440",NBUCKLEY@EXAMPLE.ORG,1910-07-03,(349)835-7258x549,Rios LLC,Francisco Harris NBUCKLEY@EXAMPLE.ORG
1,Danielle Jackson,"649 Rivera Forges Suite 276\nNorth David, WY 6...",MLOPEZ@EXAMPLE.NET,1962-10-23,(385)788-2317,"Jones, Hall and Rosales",Danielle Jackson MLOPEZ@EXAMPLE.NET
2,Poonam,New Mumbai,POONAMLOHAR@GMAIL.COM,2004-02-26,+9197463253822,Microsoft,Poonam POONAMLOHAR@GMAIL.COM
3,William Roy,"5458 Douglas Knolls\nEast Danielle, HI 37347",NPETERS@EXAMPLE.ORG,1998-10-02,457.778.0809,Hodges-Williams,William Roy NPETERS@EXAMPLE.ORG
4,Gregory Osborne,"705 Michelle Knoll\nLake Cassandrabury, MP 65153",EDWARDSKATHLEEN@EXAMPLE.COM,1982-06-05,337-692-0704x499,Krueger-Gallegos,Gregory Osborne EDWARDSKATHLEEN@EXAMPLE.COM
5,Lance Roberts,"983 Curtis Row Suite 197\nSouth Jeromeburgh, M...",AMCMAHON@EXAMPLE.NET,2004-05-04,+1-596-318-7368x45361,"Choi, Green and Suarez",Lance Roberts AMCMAHON@EXAMPLE.NET
6,Victoria Franklin,"9724 Rojas Dale Suite 692\nColemanfurt, AZ 77092",JOHN85@EXAMPLE.NET,1993-03-06,+1-553-626-2362x04119,Diaz Group,Victoria Franklin JOHN85@EXAMPLE.NET
7,Charles Mack,"210 Phillips Club Suite 212\nAndrewville, NH 2...",KELLYANDRADE@EXAMPLE.ORG,1911-05-19,766-962-8163x29485,Stephens LLC,Charles Mack KELLYANDRADE@EXAMPLE.ORG
8,Catherine Miller,"55231 James Throughway\nJessicaberg, AL 84754",YRAMOS@EXAMPLE.NET,2008-10-08,484.531.5089,"Adams, Holt and Martinez",Catherine Miller YRAMOS@EXAMPLE.NET
9,Michael Wright,"47989 Robinson Meadow\nLake Brendamouth, KS 56993",CHARLESBULLOCK@EXAMPLE.NET,1935-07-01,768-818-7370x27158,"Thomas, Lee and Johnson",Michael Wright CHARLESBULLOCK@EXAMPLE.NET

In [44]:
df.drop(columns= "Details")

,Full Name,Address,Email Address,Date of Birth,Contact Number,Company
0,Francisco Harris,"91291 James Glen\nGabrielport, FM 50440",NBUCKLEY@EXAMPLE.ORG,1910-07-03,(349)835-7258x549,Rios LLC
1,Danielle Jackson,"649 Rivera Forges Suite 276\nNorth David, WY 6...",MLOPEZ@EXAMPLE.NET,1962-10-23,(385)788-2317,"Jones, Hall and Rosales"
2,Poonam,New Mumbai,POONAMLOHAR@GMAIL.COM,2004-02-26,+9197463253822,Microsoft
3,William Roy,"5458 Douglas Knolls\nEast Danielle, HI 37347",NPETERS@EXAMPLE.ORG,1998-10-02,457.778.0809,Hodges-Williams
4,Gregory Osborne,"705 Michelle Knoll\nLake Cassandrabury, MP 65153",EDWARDSKATHLEEN@EXAMPLE.COM,1982-06-05,337-692-0704x499,Krueger-Gallegos
5,Lance Roberts,"983 Curtis Row Suite 197\nSouth Jeromeburgh, M...",AMCMAHON@EXAMPLE.NET,2004-05-04,+1-596-318-7368x45361,"Choi, Green and Suarez"
6,Victoria Franklin,"9724 Rojas Dale Suite 692\nColemanfurt, AZ 77092",JOHN85@EXAMPLE.NET,1993-03-06,+1-553-626-2362x04119,Diaz Group
7,Charles Mack,"210 Phillips Club Suite 212\nAndrewville, NH 2...",KELLYANDRADE@EXAMPLE.ORG,1911-05-19,766-962-8163x29485,Stephens LLC
8,Catherine Miller,"55231 James Throughway\nJessicaberg, AL 84754",YRAMOS@EXAMPLE.NET,2008-10-08,484.531.5089,"Adams, Holt and Martinez"
9,Michael Wright,"47989 Robinson Meadow\nLake Brendamouth, KS 56993",CHARLESBULLOCK@EXAMPLE.NET,1935-07-01,768-818-7370x27158,"Thomas, Lee and Johnson"

In [45]:
df["Details"]= df["Full Name"]+' '+ df["Email Address"]

In [46]:
df

,Full Name,Address,Email Address,Date of Birth,Contact Number,Company,Details
0,Francisco Harris,"91291 James Glen\nGabrielport, FM 50440",NBUCKLEY@EXAMPLE.ORG,1910-07-03,(349)835-7258x549,Rios LLC,Francisco Harris NBUCKLEY@EXAMPLE.ORG
1,Danielle Jackson,"649 Rivera Forges Suite 276\nNorth David, WY 6...",MLOPEZ@EXAMPLE.NET,1962-10-23,(385)788-2317,"Jones, Hall and Rosales",Danielle Jackson MLOPEZ@EXAMPLE.NET
2,Poonam,New Mumbai,POONAMLOHAR@GMAIL.COM,2004-02-26,+9197463253822,Microsoft,Poonam POONAMLOHAR@GMAIL.COM
3,William Roy,"5458 Douglas Knolls\nEast Danielle, HI 37347",NPETERS@EXAMPLE.ORG,1998-10-02,457.778.0809,Hodges-Williams,William Roy NPETERS@EXAMPLE.ORG
4,Gregory Osborne,"705 Michelle Knoll\nLake Cassandrabury, MP 65153",EDWARDSKATHLEEN@EXAMPLE.COM,1982-06-05,337-692-0704x499,Krueger-Gallegos,Gregory Osborne EDWARDSKATHLEEN@EXAMPLE.COM
5,Lance Roberts,"983 Curtis Row Suite 197\nSouth Jeromeburgh, M...",AMCMAHON@EXAMPLE.NET,2004-05-04,+1-596-318-7368x45361,"Choi, Green and Suarez",Lance Roberts AMCMAHON@EXAMPLE.NET
6,Victoria Franklin,"9724 Rojas Dale Suite 692\nColemanfurt, AZ 77092",JOHN85@EXAMPLE.NET,1993-03-06,+1-553-626-2362x04119,Diaz Group,Victoria Franklin JOHN85@EXAMPLE.NET
7,Charles Mack,"210 Phillips Club Suite 212\nAndrewville, NH 2...",KELLYANDRADE@EXAMPLE.ORG,1911-05-19,766-962-8163x29485,Stephens LLC,Charles Mack KELLYANDRADE@EXAMPLE.ORG
8,Catherine Miller,"55231 James Throughway\nJessicaberg, AL 84754",YRAMOS@EXAMPLE.NET,2008-10-08,484.531.5089,"Adams, Holt and Martinez",Catherine Miller YRAMOS@EXAMPLE.NET
9,Michael Wright,"47989 Robinson Meadow\nLake Brendamouth, KS 56993",CHARLESBULLOCK@EXAMPLE.NET,1935-07-01,768-818-7370x27158,"Thomas, Lee and Johnson",Michael Wright CHARLESBULLOCK@EXAMPLE.NET

In [47]:
df["Details"].str.split(" ", expand= True)

           0                      1                            2
0  Francisco                 Harris         NBUCKLEY@EXAMPLE.ORG
1   Danielle                Jackson           MLOPEZ@EXAMPLE.NET
2     Poonam  POONAMLOHAR@GMAIL.COM                         None
3    William                    Roy          NPETERS@EXAMPLE.ORG
4    Gregory                Osborne  EDWARDSKATHLEEN@EXAMPLE.COM
5      Lance                Roberts         AMCMAHON@EXAMPLE.NET
6   Victoria               Franklin           JOHN85@EXAMPLE.NET
7    Charles                   Mack     KELLYANDRADE@EXAMPLE.ORG
8  Catherine                 Miller           YRAMOS@EXAMPLE.NET
9    Michael                 Wright   CHARLESBULLOCK@EXAMPLE.NET

In [49]:
fake= faker.Faker('en_IN')

In [82]:
fake= faker.Faker('en_IN')
genders = ["Male", "Female", "Non-binary"]

data = [
    {
        "First name": fake.first_name(),
        "Surname": fake.last_name(),
        "Age": random.randint(18, 70),
        "City": fake.city(),
        "Hobby": random.choice(["Reading", "Gaming", "Hiking", "Cooking", "Painting", "Cycling"]),
        "Bank Name": fake.company() + " Bank",
        "Gender": random.choice(genders),
    }
    for _ in range(1000)
]

for record in data:
    print(record)

{'First name': 'Advaith', 'Surname': 'Sunder', 'Age': 25, 'City': 'Bharatpur', 'Hobby': 'Gaming', 'Bank Name': 'Dugar, Shanker and Shanker Bank', 'Gender': 'Male'}
{'First name': 'William', 'Surname': 'Sinha', 'Age': 54, 'City': 'Gorakhpur', 'Hobby': 'Gaming', 'Bank Name': 'Basu PLC Bank', 'Gender': 'Male'}
{'First name': 'Teerth', 'Surname': 'Tata', 'Age': 65, 'City': 'Kochi', 'Hobby': 'Painting', 'Bank Name': 'Kohli, Kapoor and Patla Bank', 'Gender': 'Male'}
{'First name': 'Raghav', 'Surname': 'Kata', 'Age': 49, 'City': 'Howrah', 'Hobby': 'Gaming', 'Bank Name': 'Nair Inc Bank', 'Gender': 'Non-binary'}
{'First name': 'Azad', 'Surname': 'Dua', 'Age': 57, 'City': 'Kurnool', 'Hobby': 'Reading', 'Bank Name': 'Sahota Group Bank', 'Gender': 'Male'}
{'First name': 'Samuel', 'Surname': 'Murthy', 'Age': 43, 'City': 'Gandhinagar', 'Hobby': 'Cycling', 'Bank Name': 'Krish-Bhatnagar Bank', 'Gender': 'Female'}
{'First name': 'Zaitra', 'Surname': 'Sarraf', 'Age': 18, 'City': 'Chennai', 'Hobby': 'Cooking', 'Bank Name': 'Mahal and Sons Bank', 'Gender': 'Non-binary'}
{'First name': 'Idika', 'Surname': 'Dhillon', 'Age': 48, 'City': 'Dharmavaram', 'Hobby': 'Hiking', 'Bank Name': 'Dara, Seth and Bajwa Bank', 'Gender': 'Male'}
{'First name': 'Anjali', 'Surname': 'Chaudry', 'Age': 20, 'City': 'Satna', 'Hobby': 'Hiking', 'Bank Name': 'Naik-Keer Bank', 'Gender': 'Non-binary'}
{'First name': 'Dhriti', 'Surname': 'Choudhury', 'Age': 42, 'City': 'Malda', 'Hobby': 'Cycling', 'Bank Name': 'Kara, Jain and Brar Bank', 'Gender': 'Non-binary'}
{'First name': 'Hardik', 'Surname': 'Singh', 'Age': 51, 'City': 'Bharatpur', 'Hobby': 'Painting', 'Bank Name': 'Srinivasan-Vohra Bank', 'Gender': 'Female'}
{'First name': 'Yashoda', 'Surname': 'Bassi', 'Age': 53, 'City': 'Miryalaguda', 'Hobby': 'Hiking', 'Bank Name': 'Dixit Group Bank', 'Gender': 'Non-binary'}
{'First name': 'Bhavna', 'Surname': 'Gola', 'Age': 39, 'City': 'Surat', 'Hobby': 'Cycling', 'Bank Name': 'Ravel, Barman and Shetty Bank', 'Gender': 'Non-binary'}
{'First name': 'Lajita', 'Surname': 'Viswanathan', 'Age': 36, 'City': 'Ahmedabad', 'Hobby': 'Gaming', 'Bank Name': 'Raman-Parikh Bank', 'Gender': 'Non-binary'}
{'First name': 'Ayaan', 'Surname': 'Deo', 'Age': 31, 'City': 'Ulhasnagar', 'Hobby': 'Painting', 'Bank Name': 'Pall Ltd Bank', 'Gender': 'Non-binary'}
{'First name': 'Sneha', 'Surname': 'Madan', 'Age': 43, 'City': 'Katihar', 'Hobby': 'Reading', 'Bank Name': 'Keer-Prakash Bank', 'Gender': 'Male'}
{'First name': 'Tanmayi', 'Surname': 'Walia', 'Age': 20, 'City': 'Katni', 'Hobby': 'Cycling', 'Bank Name': 'Raja, Ramaswamy and Chada Bank', 'Gender': 'Male'}
{'First name': 'Devika', 'Surname': 'Devan', 'Age': 18, 'City': 'Rajkot', 'Hobby': 'Cycling', 'Bank Name': 'Shukla, Thakkar and Srinivasan Bank', 'Gender': 'Male'}
{'First name': 'Nikita', 'Surname': 'Dhillon', 'Age': 38, 'City': 'Motihari', 'Hobby': 'Gaming', 'Bank Name': 'Bal PLC Bank', 'Gender': 'Male'}
{'First name': 'Bhavini', 'Surname': 'Kothari', 'Age': 35, 'City': 'Katni', 'Hobby': 'Hiking', 'Bank Name': 'Randhawa-Bedi Bank', 'Gender': 'Non-binary'}
{'First name': 'Raagini', 'Surname': 'Shanker', 'Age': 52, 'City': 'Allahabad', 'Hobby': 'Painting', 'Bank Name': 'Kadakia-Borah Bank', 'Gender': 'Male'}
{'First name': 'Vivaan', 'Surname': 'Sarin', 'Age': 50, 'City': 'Karaikudi', 'Hobby': 'Hiking', 'Bank Name': 'Gour, Sampath and Bandi Bank', 'Gender': 'Female'}
{'First name': 'Vamakshi', 'Surname': 'Dash', 'Age': 27, 'City': 'Hubli–Dharwad', 'Hobby': 'Reading', 'Bank Name': 'Khare, Shankar and Mander Bank', 'Gender': 'Male'}
{'First name': 'Elijah', 'Surname': 'Patil', 'Age': 18, 'City': 'Imphal', 'Hobby': 'Painting', 'Bank Name': 'Kalla, Sarin and Dey Bank', 'Gender': 'Female'}
{'First name': 'Tara', 'Surname': 'Chaudry', 'Age': 18, 'City': 'Ramagundam', 'Hobby': 'Cooking', 'Bank Name': 'Thakkar-Trivedi Bank', 'Gender': 'Non-binary'}
{'First name': 'Ayush', 'Surname': 'Verma', 'Age': 37, 'City': 'Mango', 'Hobby': 'Cycling', 'Bank Name': 'Vig Group Bank', 'Gender': 'Non-binary'}
{'First name': 'Hredhaan', 'Surname': 'Kakar', 'Age': 46, 'City': 'Rajahmundry', 'Hobby': 'Painting', 'Bank Name': 'Sankaran, Munshi and Kala Bank', 'Gender': 'Female'}
{'First name': 'Waida', 'Surname': 'Dar', 'Age': 27, 'City': 'Jamshedpur', 'Hobby': 'Cooking', 'Bank Name': 'Bhatt-Gupta Bank', 'Gender': 'Female'}
{'First name': 'Harish', 'Surname': 'Bhardwaj', 'Age': 46, 'City': 'Kanpur', 'Hobby': 'Gaming', 'Bank Name': 'Pandya-Ramesh Bank', 'Gender': 'Male'}
{'First name': 'Tejas', 'Surname': 'Loke', 'Age': 61, 'City': 'Madhyamgram', 'Hobby': 'Hiking', 'Bank Name': 'Lal-Dutta Bank', 'Gender': 'Non-binary'}
{'First name': 'William', 'Surname': 'Shan', 'Age': 45, 'City': 'Naihati', 'Hobby': 'Reading', 'Bank Name': 'Varkey-Sami Bank', 'Gender': 'Male'}
{'First name': 'Jagat', 'Surname': 'Sankaran', 'Age': 39, 'City': 'Delhi', 'Hobby': 'Gaming', 'Bank Name': 'Jain-Biswas Bank', 'Gender': 'Non-binary'}
{'First name': 'Lavanya', 'Surname': 'Narayanan', 'Age': 39, 'City': 'Udaipur', 'Hobby': 'Reading', 'Bank Name': 'Kala, Bhatti and Vig Bank', 'Gender': 'Non-binary'}
{'First name': 'Nitara', 'Surname': 'Koshy', 'Age': 50, 'City': 'Rohtak', 'Hobby': 'Gaming', 'Bank Name': 'Nagar, Mitter and Prakash Bank', 'Gender': 'Male'}
{'First name': 'Sudiksha', 'Surname': 'Mand', 'Age': 70, 'City': 'Surat', 'Hobby': 'Cycling', 'Bank Name': 'Bassi-Yogi Bank', 'Gender': 'Male'}
{'First name': 'Avi', 'Surname': 'Dada', 'Age': 57, 'City': 'Sri Ganganagar', 'Hobby': 'Hiking', 'Bank Name': 'Nayar, Kala and Dave Bank', 'Gender': 'Male'}
{'First name': 'Anthony', 'Surname': 'Bedi', 'Age': 33, 'City': 'Arrah', 'Hobby': 'Painting', 'Bank Name': 'Sandal Ltd Bank', 'Gender': 'Non-binary'}
{'First name': 'Raksha', 'Surname': 'Wason', 'Age': 21, 'City': 'Aurangabad', 'Hobby': 'Cooking', 'Bank Name': 'Choudhury Ltd Bank', 'Gender': 'Non-binary'}
{'First name': 'Hemangini', 'Surname': 'Sabharwal', 'Age': 51, 'City': 'Bhusawal', 'Hobby': 'Painting', 'Bank Name': 'Sachdeva, Chopra and Choudhry Bank', 'Gender': 'Female'}
{'First name': 'Chatresh', 'Surname': 'Chaudhary', 'Age': 59, 'City': 'Parbhani', 'Hobby': 'Gaming', 'Bank Name': 'Naik-Kaul Bank', 'Gender': 'Female'}
{'First name': 'Teerth', 'Surname': 'Saraf', 'Age': 54, 'City': 'Guntur', 'Hobby': 'Reading', 'Bank Name': 'Nayak, Vaidya and Bhattacharyya Bank', 'Gender': 'Female'}
{'First name': 'Qasim', 'Surname': 'Bhatia', 'Age': 27, 'City': 'Ambala', 'Hobby': 'Cycling', 'Bank Name': 'Chadha, Randhawa and Oommen Bank', 'Gender': 'Non-binary'}
{'First name': 'Laban', 'Surname': 'Sha', 'Age': 26, 'City': 'Indore', 'Hobby': 'Hiking', 'Bank Name': 'Dugar Inc Bank', 'Gender': 'Non-binary'}
{'First name': 'Praneel', 'Surname': 'Khatri', 'Age': 27, 'City': 'Karnal', 'Hobby': 'Gaming', 'Bank Name': 'Natarajan-Nair Bank', 'Gender': 'Female'}
{'First name': 'Ikbal', 'Surname': 'Sarraf', 'Age': 47, 'City': 'Agartala', 'Hobby': 'Cooking', 'Bank Name': 'Singh-Savant Bank', 'Gender': 'Non-binary'}
{'First name': 'Victor', 'Surname': 'Din', 'Age': 45, 'City': 'Ajmer', 'Hobby': 'Hiking', 'Bank Name': 'Toor-Naik Bank', 'Gender': 'Male'}
{'First name': 'Unni', 'Surname': 'Kunda', 'Age': 37, 'City': 'Latur', 'Hobby': 'Gaming', 'Bank Name': 'Bava-Ramesh Bank', 'Gender': 'Non-binary'}
{'First name': 'Aayush', 'Surname': 'Ray', 'Age': 46, 'City': 'Sambhal', 'Hobby': 'Cooking', 'Bank Name': 'Choudhary, Gill and Pingle Bank', 'Gender': 'Non-binary'}
{'First name': 'Vaishnavi', 'Surname': 'Borde', 'Age': 64, 'City': 'Mango', 'Hobby': 'Hiking', 'Bank Name': 'Patel-Bail Bank', 'Gender': 'Female'}
{'First name': 'Ikshita', 'Surname': 'Saha', 'Age': 35, 'City': 'Udupi', 'Hobby': 'Reading', 'Bank Name': 'Patla Ltd Bank', 'Gender': 'Male'}
{'First name': 'Elijah', 'Surname': 'Sridhar', 'Age': 51, 'City': 'Secunderabad', 'Hobby': 'Painting', 'Bank Name': 'More, Bhatt and Randhawa Bank', 'Gender': 'Female'}
{'First name': 'Irya', 'Surname': 'Seshadri', 'Age': 23, 'City': 'Ghaziabad', 'Hobby': 'Hiking', 'Bank Name': 'Ramaswamy-Varma Bank', 'Gender': 'Male'}
{'First name': 'Atharv', 'Surname': 'Narain', 'Age': 32, 'City': 'Hyderabad', 'Hobby': 'Painting', 'Bank Name': 'Dhaliwal Inc Bank', 'Gender': 'Non-binary'}
{'First name': 'Warjas', 'Surname': 'Kata', 'Age': 26, 'City': 'Nizamabad', 'Hobby': 'Hiking', 'Bank Name': 'Raja LLC Bank', 'Gender': 'Non-binary'}
{'First name': 'Harshil', 'Surname': 'Ramesh', 'Age': 35, 'City': 'Panipat', 'Hobby': 'Cooking', 'Bank Name': 'Joshi-Thakur Bank', 'Gender': 'Male'}
{'First name': 'Qushi', 'Surname': 'Batra', 'Age': 62, 'City': 'Munger', 'Hobby': 'Cooking', 'Bank Name': 'Kota Ltd Bank', 'Gender': 'Female'}
{'First name': 'Nathan', 'Surname': 'Taneja', 'Age': 41, 'City': 'Rajpur Sonarpur', 'Hobby': 'Gaming', 'Bank Name': 'Raj, Dara and Kunda Bank', 'Gender': 'Non-binary'}
{'First name': 'Mitali', 'Surname': 'Sane', 'Age': 62, 'City': 'Hajipur', 'Hobby': 'Hiking', 'Bank Name': 'Rout-Sarna Bank', 'Gender': 'Male'}
{'First name': 'Bishakha', 'Surname': 'Roy', 'Age': 61, 'City': 'Bathinda', 'Hobby': 'Hiking', 'Bank Name': 'Sani, Ramachandran and Pradhan Bank', 'Gender': 'Female'}
{'First name': 'Damini', 'Surname': 'Dube', 'Age': 52, 'City': 'Kulti', 'Hobby': 'Gaming', 'Bank Name': 'Raval Group Bank', 'Gender': 'Female'}
{'First name': 'Wakeeta', 'Surname': 'Divan', 'Age': 46, 'City': 'Bharatpur', 'Hobby': 'Hiking', 'Bank Name': 'Jaggi-Natt Bank', 'Gender': 'Non-binary'}
{'First name': 'Farhan', 'Surname': 'Aggarwal', 'Age': 60, 'City': 'Mirzapur', 'Hobby': 'Cooking', 'Bank Name': 'Gara, Ganesan and Zacharia Bank', 'Gender': 'Non-binary'}
{'First name': 'Isaac', 'Surname': 'Atwal', 'Age': 41, 'City': 'Rohtak', 'Hobby': 'Reading', 'Bank Name': 'Mannan PLC Bank', 'Gender': 'Female'}
{'First name': 'Faraj', 'Surname': 'Devi', 'Age': 69, 'City': 'Burhanpur', 'Hobby': 'Cooking', 'Bank Name': 'Vig PLC Bank', 'Gender': 'Female'}
{'First name': 'Vasatika', 'Surname': 'Rajagopal', 'Age': 61, 'City': 'Guntakal', 'Hobby': 'Cooking', 'Bank Name': 'Kala, Devi and Pillay Bank', 'Gender': 'Female'}
{'First name': 'Shivansh', 'Surname': 'Mahal', 'Age': 29, 'City': 'Muzaffarnagar', 'Hobby': 'Painting', 'Bank Name': 'Sachdeva-Gandhi Bank', 'Gender': 'Female'}
{'First name': 'Advik', 'Surname': 'Mitra', 'Age': 45, 'City': 'Nangloi Jat', 'Hobby': 'Cooking', 'Bank Name': 'Shetty, Suri and Lala Bank', 'Gender': 'Non-binary'}
{'First name': 'Sudiksha', 'Surname': 'Arya', 'Age': 29, 'City': 'Ramagundam', 'Hobby': 'Reading', 'Bank Name': 'Sarraf-Gole Bank', 'Gender': 'Non-binary'}
{'First name': 'William', 'Surname': 'Patil', 'Age': 56, 'City': 'Kulti', 'Hobby': 'Hiking', 'Bank Name': 'Tailor Inc Bank', 'Gender': 'Male'}
{'First name': 'Nicholas', 'Surname': 'Brar', 'Age': 69, 'City': 'Baranagar', 'Hobby': 'Cycling', 'Bank Name': 'Bandi, Viswanathan and Raval Bank', 'Gender': 'Female'}
{'First name': 'Divya', 'Surname': 'Patla', 'Age': 59, 'City': 'Naihati', 'Hobby': 'Painting', 'Bank Name': 'Brahmbhatt Ltd Bank', 'Gender': 'Female'}
{'First name': 'Dayita', 'Surname': 'Narula', 'Age': 45, 'City': 'Durg', 'Hobby': 'Reading', 'Bank Name': 'Jayaraman, Bali and Atwal Bank', 'Gender': 'Female'}
{'First name': 'Dhruv', 'Surname': 'Sabharwal', 'Age': 42, 'City': 'Surat', 'Hobby': 'Cycling', 'Bank Name': 'Vohra, Kamdar and Chaudry Bank', 'Gender': 'Non-binary'}
{'First name': 'Yamini', 'Surname': 'Prabhu', 'Age': 66, 'City': 'Muzaffarpur', 'Hobby': 'Painting', 'Bank Name': 'Sarma PLC Bank', 'Gender': 'Non-binary'}
{'First name': 'Jacob', 'Surname': 'Kibe', 'Age': 34, 'City': 'Jaunpur', 'Hobby': 'Painting', 'Bank Name': 'Chokshi-Raghavan Bank', 'Gender': 'Female'}
{'First name': 'Frado', 'Surname': 'Upadhyay', 'Age': 32, 'City': 'Patiala', 'Hobby': 'Cycling', 'Bank Name': 'Kade PLC Bank', 'Gender': 'Male'}
{'First name': 'Nakul', 'Surname': 'Palan', 'Age': 21, 'City': 'Chinsurah', 'Hobby': 'Reading', 'Bank Name': 'Chatterjee, Vig and Choudhury Bank', 'Gender': 'Male'}
{'First name': 'Ranbir', 'Surname': 'Verma', 'Age': 38, 'City': 'Silchar', 'Hobby': 'Cooking', 'Bank Name': 'Peri-Deol Bank', 'Gender': 'Female'}
{'First name': 'Jeevika', 'Surname': 'Saini', 'Age': 68, 'City': 'Kavali', 'Hobby': 'Reading', 'Bank Name': 'Bobal, Mandal and Tak Bank', 'Gender': 'Male'}
{'First name': 'Zaid', 'Surname': 'Radhakrishnan', 'Age': 51, 'City': 'Naihati', 'Hobby': 'Reading', 'Bank Name': 'Borde Ltd Bank', 'Gender': 'Male'}
{'First name': 'Ayush', 'Surname': 'Pandey', 'Age': 45, 'City': 'Pondicherry', 'Hobby': 'Reading', 'Bank Name': 'Goyal, Madan and Kakar Bank', 'Gender': 'Female'}
{'First name': 'Garima', 'Surname': 'Pant', 'Age': 25, 'City': 'Mau', 'Hobby': 'Cycling', 'Bank Name': 'Sharaf PLC Bank', 'Gender': 'Male'}
{'First name': 'Adweta', 'Surname': 'Ravel', 'Age': 44, 'City': 'Howrah', 'Hobby': 'Painting', 'Bank Name': 'Bali-Behl Bank', 'Gender': 'Non-binary'}
{'First name': 'Daksha', 'Surname': 'Karan', 'Age': 65, 'City': 'Baranagar', 'Hobby': 'Hiking', 'Bank Name': 'Venkataraman-Ganesan Bank', 'Gender': 'Female'}
{'First name': 'Shravya', 'Surname': 'Dey', 'Age': 36, 'City': 'Chittoor', 'Hobby': 'Reading', 'Bank Name': 'Mander-Seth Bank', 'Gender': 'Non-binary'}
{'First name': 'Chakradev', 'Surname': 'Misra', 'Age': 48, 'City': 'Gaya', 'Hobby': 'Hiking', 'Bank Name': 'Dalal-Mitra Bank', 'Gender': 'Male'}
{'First name': 'Ekantika', 'Surname': 'Srinivas', 'Age': 48, 'City': 'Hospet', 'Hobby': 'Reading', 'Bank Name': 'Viswanathan-Bhavsar Bank', 'Gender': 'Male'}
{'First name': 'Ishita', 'Surname': 'Palla', 'Age': 35, 'City': 'South Dumdum', 'Hobby': 'Cycling', 'Bank Name': 'Shroff PLC Bank', 'Gender': 'Female'}
{'First name': 'Guneet', 'Surname': 'Chauhan', 'Age': 34, 'City': 'Sambhal', 'Hobby': 'Hiking', 'Bank Name': 'Mane, Gaba and Sura Bank', 'Gender': 'Female'}
{'First name': 'Zilmil', 'Surname': 'Parmar', 'Age': 52, 'City': 'Panvel', 'Hobby': 'Painting', 'Bank Name': 'Murthy Group Bank', 'Gender': 'Male'}
{'First name': 'Zinal', 'Surname': 'Sodhi', 'Age': 25, 'City': 'Panipat', 'Hobby': 'Cooking', 'Bank Name': 'Bumb, Kanda and Prabhakar Bank', 'Gender': 'Male'}
{'First name': 'Samar', 'Surname': 'Kar', 'Age': 51, 'City': 'Karawal Nagar', 'Hobby': 'Cycling', 'Bank Name': 'Mammen, Butala and Gulati Bank', 'Gender': 'Male'}
{'First name': 'Jeevika', 'Surname': 'Kota', 'Age': 56, 'City': 'Madanapalle', 'Hobby': 'Cycling', 'Bank Name': 'Hans LLC Bank', 'Gender': 'Non-binary'}
{'First name': 'Jacob', 'Surname': 'Deo', 'Age': 50, 'City': 'Thoothukudi', 'Hobby': 'Gaming', 'Bank Name': 'Sama Ltd Bank', 'Gender': 'Male'}
{'First name': 'Harini', 'Surname': 'Sant', 'Age': 20, 'City': 'Uluberia', 'Hobby': 'Painting', 'Bank Name': 'Narayanan-Sood Bank', 'Gender': 'Male'}
{'First name': 'Zinal', 'Surname': 'Behl', 'Age': 68, 'City': 'Bareilly', 'Hobby': 'Gaming', 'Bank Name': 'Mittal, Raman and Natarajan Bank', 'Gender': 'Male'}
{'First name': 'Pushti', 'Surname': 'Ahluwalia', 'Age': 24, 'City': 'Jorhat', 'Hobby': 'Painting', 'Bank Name': 'Rout, Kara and Chada Bank', 'Gender': 'Male'}
{'First name': 'Tanveer', 'Surname': 'Lad', 'Age': 60, 'City': 'Pali', 'Hobby': 'Gaming', 'Bank Name': 'Sachar LLC Bank', 'Gender': 'Non-binary'}
{'First name': 'Devansh', 'Surname': 'Prabhakar', 'Age': 28, 'City': 'Tiruppur', 'Hobby': 'Cooking', 'Bank Name': 'Chakrabarti, Dalal and Palla Bank', 'Gender': 'Non-binary'}
{'First name': 'Faris', 'Surname': 'Kalita', 'Age': 32, 'City': 'Durgapur', 'Hobby': 'Hiking', 'Bank Name': 'Krishnamurthy PLC Bank', 'Gender': 'Female'}
{'First name': 'Elijah', 'Surname': 'Gill', 'Age': 26, 'City': 'Mira-Bhayandar', 'Hobby': 'Reading', 'Bank Name': 'Setty Ltd Bank', 'Gender': 'Female'}
{'First name': 'Jagdish', 'Surname': 'Chaudhary', 'Age': 34, 'City': 'Silchar', 'Hobby': 'Reading', 'Bank Name': 'Dar, Buch and Bal Bank', 'Gender': 'Female'}
{'First name': 'Zaid', 'Surname': 'Mukherjee', 'Age': 41, 'City': 'Udaipur', 'Hobby': 'Painting', 'Bank Name': 'Doctor-Bhatia Bank', 'Gender': 'Male'}
{'First name': 'Hredhaan', 'Surname': 'Bera', 'Age': 67, 'City': 'Satna', 'Hobby': 'Cooking', 'Bank Name': 'Ahuja LLC Bank', 'Gender': 'Female'}
{'First name': 'Chandran', 'Surname': 'Bakshi', 'Age': 44, 'City': 'Dewas', 'Hobby': 'Painting', 'Bank Name': 'Bora Ltd Bank', 'Gender': 'Male'}
{'First name': 'Geetika', 'Surname': 'Padmanabhan', 'Age': 30, 'City': 'Bihar Sharif', 'Hobby': 'Cycling', 'Bank Name': 'Majumdar, Ray and Chawla Bank', 'Gender': 'Male'}
{'First name': 'Indali', 'Surname': 'Arya', 'Age': 25, 'City': 'Nangloi Jat', 'Hobby': 'Cooking', 'Bank Name': 'Chaudhary, Banerjee and Dalal Bank', 'Gender': 'Male'}
{'First name': 'Indali', 'Surname': 'Sundaram', 'Age': 69, 'City': 'Singrauli', 'Hobby': 'Painting', 'Bank Name': 'Loke-Bhalla Bank', 'Gender': 'Female'}
{'First name': 'Wyatt', 'Surname': 'Dash', 'Age': 41, 'City': 'Mathura', 'Hobby': 'Painting', 'Bank Name': 'Halder Inc Bank', 'Gender': 'Female'}
{'First name': 'Jairaj', 'Surname': 'Kala', 'Age': 21, 'City': 'Mathura', 'Hobby': 'Gaming', 'Bank Name': 'Gera-Sarma Bank', 'Gender': 'Male'}
{'First name': 'Aradhana', 'Surname': 'Sheth', 'Age': 20, 'City': 'Meerut', 'Hobby': 'Reading', 'Bank Name': 'Sarna, Mander and Pingle Bank', 'Gender': 'Non-binary'}
{'First name': 'Indrajit', 'Surname': 'Bansal', 'Age': 67, 'City': 'Berhampur', 'Hobby': 'Painting', 'Bank Name': 'Ahuja-Parikh Bank', 'Gender': 'Female'}
{'First name': 'Radhika', 'Surname': 'Morar', 'Age': 37, 'City': 'Saharsa', 'Hobby': 'Cooking', 'Bank Name': 'Randhawa, Misra and Prabhu Bank', 'Gender': 'Non-binary'}
{'First name': 'Wridesh', 'Surname': 'Gara', 'Age': 24, 'City': 'Sambalpur', 'Hobby': 'Reading', 'Bank Name': 'Joshi, Buch and Talwar Bank', 'Gender': 'Male'}
{'First name': 'Panini', 'Surname': 'Sahni', 'Age': 45, 'City': 'Hospet', 'Hobby': 'Cooking', 'Bank Name': 'Banik PLC Bank', 'Gender': 'Male'}
{'First name': 'Eta', 'Surname': 'Narayanan', 'Age': 60, 'City': 'Kharagpur', 'Hobby': 'Painting', 'Bank Name': 'Karpe, Saraf and Nanda Bank', 'Gender': 'Non-binary'}
{'First name': 'Zehaan', 'Surname': 'Dua', 'Age': 69, 'City': 'Bokaro', 'Hobby': 'Gaming', 'Bank Name': 'Johal Group Bank', 'Gender': 'Male'}
{'First name': 'Qabil', 'Surname': 'Nayar', 'Age': 18, 'City': 'Chandigarh', 'Hobby': 'Hiking', 'Bank Name': 'Savant, Choudhry and Setty Bank', 'Gender': 'Female'}
{'First name': 'Abha', 'Surname': 'Mohanty', 'Age': 39, 'City': 'Amritsar', 'Hobby': 'Painting', 'Bank Name': 'Boase Group Bank', 'Gender': 'Male'}
{'First name': 'Odika', 'Surname': 'Sani', 'Age': 35, 'City': 'Raebareli', 'Hobby': 'Cycling', 'Bank Name': 'Loyal, Nath and Ravi Bank', 'Gender': 'Non-binary'}
{'First name': 'Anthony', 'Surname': 'Prasad', 'Age': 67, 'City': 'Muzaffarnagar', 'Hobby': 'Cycling', 'Bank Name': 'Konda-Atwal Bank', 'Gender': 'Male'}
{'First name': 'Ladli', 'Surname': 'Chowdhury', 'Age': 49, 'City': 'Vijayanagaram', 'Hobby': 'Reading', 'Bank Name': 'Gera, Tella and Ganesan Bank', 'Gender': 'Female'}
{'First name': 'Liam', 'Surname': 'Garg', 'Age': 56, 'City': 'Ongole', 'Hobby': 'Reading', 'Bank Name': 'Narula-Yohannan Bank', 'Gender': 'Male'}
{'First name': 'Kamya', 'Surname': 'Shetty', 'Age': 26, 'City': 'Mirzapur', 'Hobby': 'Hiking', 'Bank Name': 'Goswami Inc Bank', 'Gender': 'Female'}
{'First name': 'Abdul', 'Surname': 'Karnik', 'Age': 45, 'City': 'Serampore', 'Hobby': 'Gaming', 'Bank Name': 'Kara and Sons Bank', 'Gender': 'Female'}
{'First name': 'Kai', 'Surname': 'Sani', 'Age': 37, 'City': 'Dehri', 'Hobby': 'Reading', 'Bank Name': 'Dutt-Bedi Bank', 'Gender': 'Non-binary'}
{'First name': 'George', 'Surname': 'Dhingra', 'Age': 52, 'City': 'Purnia', 'Hobby': 'Cooking', 'Bank Name': 'Joshi, Som and Venkataraman Bank', 'Gender': 'Female'}
{'First name': 'Hamsini', 'Surname': 'Chahal', 'Age': 53, 'City': 'Dhule', 'Hobby': 'Painting', 'Bank Name': 'Ganesan, Krishnamurthy and Sha Bank', 'Gender': 'Non-binary'}
{'First name': 'Vrinda', 'Surname': 'Sehgal', 'Age': 63, 'City': 'Guwahati', 'Hobby': 'Reading', 'Bank Name': 'Sangha-Mistry Bank', 'Gender': 'Male'}

In [83]:
data

[{'First name': 'Advaith',
  'Surname': 'Sunder',
  'Age': 25,
  'City': 'Bharatpur',
  'Hobby': 'Gaming',
  'Bank Name': 'Dugar, Shanker and Shanker Bank',
  'Gender': 'Male'},
 {'First name': 'William',
  'Surname': 'Sinha',
  'Age': 54,
  'City': 'Gorakhpur',
  'Hobby': 'Gaming',
  'Bank Name': 'Basu PLC Bank',
  'Gender': 'Male'},
 {'First name': 'Teerth',
  'Surname': 'Tata',
  'Age': 65,
  'City': 'Kochi',
  'Hobby': 'Painting',
  'Bank Name': 'Kohli, Kapoor and Patla Bank',
  'Gender': 'Male'},
 {'First name': 'Raghav',
  'Surname': 'Kata',
  'Age': 49,
  'City': 'Howrah',
  'Hobby': 'Gaming',
  'Bank Name': 'Nair Inc Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Azad',
  'Surname': 'Dua',
  'Age': 57,
  'City': 'Kurnool',
  'Hobby': 'Reading',
  'Bank Name': 'Sahota Group Bank',
  'Gender': 'Male'},
 {'First name': 'Samuel',
  'Surname': 'Murthy',
  'Age': 43,
  'City': 'Gandhinagar',
  'Hobby': 'Cycling',
  'Bank Name': 'Krish-Bhatnagar Bank',
  'Gender': 'Female'},
 {'First name': 'Zaitra',
  'Surname': 'Sarraf',
  'Age': 18,
  'City': 'Chennai',
  'Hobby': 'Cooking',
  'Bank Name': 'Mahal and Sons Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Idika',
  'Surname': 'Dhillon',
  'Age': 48,
  'City': 'Dharmavaram',
  'Hobby': 'Hiking',
  'Bank Name': 'Dara, Seth and Bajwa Bank',
  'Gender': 'Male'},
 {'First name': 'Anjali',
  'Surname': 'Chaudry',
  'Age': 20,
  'City': 'Satna',
  'Hobby': 'Hiking',
  'Bank Name': 'Naik-Keer Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Dhriti',
  'Surname': 'Choudhury',
  'Age': 42,
  'City': 'Malda',
  'Hobby': 'Cycling',
  'Bank Name': 'Kara, Jain and Brar Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Hardik',
  'Surname': 'Singh',
  'Age': 51,
  'City': 'Bharatpur',
  'Hobby': 'Painting',
  'Bank Name': 'Srinivasan-Vohra Bank',
  'Gender': 'Female'},
 {'First name': 'Yashoda',
  'Surname': 'Bassi',
  'Age': 53,
  'City': 'Miryalaguda',
  'Hobby': 'Hiking',
  'Bank Name': 'Dixit Group Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Bhavna',
  'Surname': 'Gola',
  'Age': 39,
  'City': 'Surat',
  'Hobby': 'Cycling',
  'Bank Name': 'Ravel, Barman and Shetty Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Lajita',
  'Surname': 'Viswanathan',
  'Age': 36,
  'City': 'Ahmedabad',
  'Hobby': 'Gaming',
  'Bank Name': 'Raman-Parikh Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Ayaan',
  'Surname': 'Deo',
  'Age': 31,
  'City': 'Ulhasnagar',
  'Hobby': 'Painting',
  'Bank Name': 'Pall Ltd Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Sneha',
  'Surname': 'Madan',
  'Age': 43,
  'City': 'Katihar',
  'Hobby': 'Reading',
  'Bank Name': 'Keer-Prakash Bank',
  'Gender': 'Male'},
 {'First name': 'Tanmayi',
  'Surname': 'Walia',
  'Age': 20,
  'City': 'Katni',
  'Hobby': 'Cycling',
  'Bank Name': 'Raja, Ramaswamy and Chada Bank',
  'Gender': 'Male'},
 {'First name': 'Devika',
  'Surname': 'Devan',
  'Age': 18,
  'City': 'Rajkot',
  'Hobby': 'Cycling',
  'Bank Name': 'Shukla, Thakkar and Srinivasan Bank',
  'Gender': 'Male'},
 {'First name': 'Nikita',
  'Surname': 'Dhillon',
  'Age': 38,
  'City': 'Motihari',
  'Hobby': 'Gaming',
  'Bank Name': 'Bal PLC Bank',
  'Gender': 'Male'},
 {'First name': 'Bhavini',
  'Surname': 'Kothari',
  'Age': 35,
  'City': 'Katni',
  'Hobby': 'Hiking',
  'Bank Name': 'Randhawa-Bedi Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Raagini',
  'Surname': 'Shanker',
  'Age': 52,
  'City': 'Allahabad',
  'Hobby': 'Painting',
  'Bank Name': 'Kadakia-Borah Bank',
  'Gender': 'Male'},
 {'First name': 'Vivaan',
  'Surname': 'Sarin',
  'Age': 50,
  'City': 'Karaikudi',
  'Hobby': 'Hiking',
  'Bank Name': 'Gour, Sampath and Bandi Bank',
  'Gender': 'Female'},
 {'First name': 'Vamakshi',
  'Surname': 'Dash',
  'Age': 27,
  'City': 'Hubli–Dharwad',
  'Hobby': 'Reading',
  'Bank Name': 'Khare, Shankar and Mander Bank',
  'Gender': 'Male'},
 {'First name': 'Elijah',
  'Surname': 'Patil',
  'Age': 18,
  'City': 'Imphal',
  'Hobby': 'Painting',
  'Bank Name': 'Kalla, Sarin and Dey Bank',
  'Gender': 'Female'},
 {'First name': 'Tara',
  'Surname': 'Chaudry',
  'Age': 18,
  'City': 'Ramagundam',
  'Hobby': 'Cooking',
  'Bank Name': 'Thakkar-Trivedi Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Ayush',
  'Surname': 'Verma',
  'Age': 37,
  'City': 'Mango',
  'Hobby': 'Cycling',
  'Bank Name': 'Vig Group Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Hredhaan',
  'Surname': 'Kakar',
  'Age': 46,
  'City': 'Rajahmundry',
  'Hobby': 'Painting',
  'Bank Name': 'Sankaran, Munshi and Kala Bank',
  'Gender': 'Female'},
 {'First name': 'Waida',
  'Surname': 'Dar',
  'Age': 27,
  'City': 'Jamshedpur',
  'Hobby': 'Cooking',
  'Bank Name': 'Bhatt-Gupta Bank',
  'Gender': 'Female'},
 {'First name': 'Harish',
  'Surname': 'Bhardwaj',
  'Age': 46,
  'City': 'Kanpur',
  'Hobby': 'Gaming',
  'Bank Name': 'Pandya-Ramesh Bank',
  'Gender': 'Male'},
 {'First name': 'Tejas',
  'Surname': 'Loke',
  'Age': 61,
  'City': 'Madhyamgram',
  'Hobby': 'Hiking',
  'Bank Name': 'Lal-Dutta Bank',
  'Gender': 'Non-binary'},
 {'First name': 'William',
  'Surname': 'Shan',
  'Age': 45,
  'City': 'Naihati',
  'Hobby': 'Reading',
  'Bank Name': 'Varkey-Sami Bank',
  'Gender': 'Male'},
 {'First name': 'Jagat',
  'Surname': 'Sankaran',
  'Age': 39,
  'City': 'Delhi',
  'Hobby': 'Gaming',
  'Bank Name': 'Jain-Biswas Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Lavanya',
  'Surname': 'Narayanan',
  'Age': 39,
  'City': 'Udaipur',
  'Hobby': 'Reading',
  'Bank Name': 'Kala, Bhatti and Vig Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Nitara',
  'Surname': 'Koshy',
  'Age': 50,
  'City': 'Rohtak',
  'Hobby': 'Gaming',
  'Bank Name': 'Nagar, Mitter and Prakash Bank',
  'Gender': 'Male'},
 {'First name': 'Sudiksha',
  'Surname': 'Mand',
  'Age': 70,
  'City': 'Surat',
  'Hobby': 'Cycling',
  'Bank Name': 'Bassi-Yogi Bank',
  'Gender': 'Male'},
 {'First name': 'Avi',
  'Surname': 'Dada',
  'Age': 57,
  'City': 'Sri Ganganagar',
  'Hobby': 'Hiking',
  'Bank Name': 'Nayar, Kala and Dave Bank',
  'Gender': 'Male'},
 {'First name': 'Anthony',
  'Surname': 'Bedi',
  'Age': 33,
  'City': 'Arrah',
  'Hobby': 'Painting',
  'Bank Name': 'Sandal Ltd Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Raksha',
  'Surname': 'Wason',
  'Age': 21,
  'City': 'Aurangabad',
  'Hobby': 'Cooking',
  'Bank Name': 'Choudhury Ltd Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Hemangini',
  'Surname': 'Sabharwal',
  'Age': 51,
  'City': 'Bhusawal',
  'Hobby': 'Painting',
  'Bank Name': 'Sachdeva, Chopra and Choudhry Bank',
  'Gender': 'Female'},
 {'First name': 'Chatresh',
  'Surname': 'Chaudhary',
  'Age': 59,
  'City': 'Parbhani',
  'Hobby': 'Gaming',
  'Bank Name': 'Naik-Kaul Bank',
  'Gender': 'Female'},
 {'First name': 'Teerth',
  'Surname': 'Saraf',
  'Age': 54,
  'City': 'Guntur',
  'Hobby': 'Reading',
  'Bank Name': 'Nayak, Vaidya and Bhattacharyya Bank',
  'Gender': 'Female'},
 {'First name': 'Qasim',
  'Surname': 'Bhatia',
  'Age': 27,
  'City': 'Ambala',
  'Hobby': 'Cycling',
  'Bank Name': 'Chadha, Randhawa and Oommen Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Laban',
  'Surname': 'Sha',
  'Age': 26,
  'City': 'Indore',
  'Hobby': 'Hiking',
  'Bank Name': 'Dugar Inc Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Praneel',
  'Surname': 'Khatri',
  'Age': 27,
  'City': 'Karnal',
  'Hobby': 'Gaming',
  'Bank Name': 'Natarajan-Nair Bank',
  'Gender': 'Female'},
 {'First name': 'Ikbal',
  'Surname': 'Sarraf',
  'Age': 47,
  'City': 'Agartala',
  'Hobby': 'Cooking',
  'Bank Name': 'Singh-Savant Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Victor',
  'Surname': 'Din',
  'Age': 45,
  'City': 'Ajmer',
  'Hobby': 'Hiking',
  'Bank Name': 'Toor-Naik Bank',
  'Gender': 'Male'},
 {'First name': 'Unni',
  'Surname': 'Kunda',
  'Age': 37,
  'City': 'Latur',
  'Hobby': 'Gaming',
  'Bank Name': 'Bava-Ramesh Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Aayush',
  'Surname': 'Ray',
  'Age': 46,
  'City': 'Sambhal',
  'Hobby': 'Cooking',
  'Bank Name': 'Choudhary, Gill and Pingle Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Vaishnavi',
  'Surname': 'Borde',
  'Age': 64,
  'City': 'Mango',
  'Hobby': 'Hiking',
  'Bank Name': 'Patel-Bail Bank',
  'Gender': 'Female'},
 {'First name': 'Ikshita',
  'Surname': 'Saha',
  'Age': 35,
  'City': 'Udupi',
  'Hobby': 'Reading',
  'Bank Name': 'Patla Ltd Bank',
  'Gender': 'Male'},
 {'First name': 'Elijah',
  'Surname': 'Sridhar',
  'Age': 51,
  'City': 'Secunderabad',
  'Hobby': 'Painting',
  'Bank Name': 'More, Bhatt and Randhawa Bank',
  'Gender': 'Female'},
 {'First name': 'Irya',
  'Surname': 'Seshadri',
  'Age': 23,
  'City': 'Ghaziabad',
  'Hobby': 'Hiking',
  'Bank Name': 'Ramaswamy-Varma Bank',
  'Gender': 'Male'},
 {'First name': 'Atharv',
  'Surname': 'Narain',
  'Age': 32,
  'City': 'Hyderabad',
  'Hobby': 'Painting',
  'Bank Name': 'Dhaliwal Inc Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Warjas',
  'Surname': 'Kata',
  'Age': 26,
  'City': 'Nizamabad',
  'Hobby': 'Hiking',
  'Bank Name': 'Raja LLC Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Harshil',
  'Surname': 'Ramesh',
  'Age': 35,
  'City': 'Panipat',
  'Hobby': 'Cooking',
  'Bank Name': 'Joshi-Thakur Bank',
  'Gender': 'Male'},
 {'First name': 'Qushi',
  'Surname': 'Batra',
  'Age': 62,
  'City': 'Munger',
  'Hobby': 'Cooking',
  'Bank Name': 'Kota Ltd Bank',
  'Gender': 'Female'},
 {'First name': 'Nathan',
  'Surname': 'Taneja',
  'Age': 41,
  'City': 'Rajpur Sonarpur',
  'Hobby': 'Gaming',
  'Bank Name': 'Raj, Dara and Kunda Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Mitali',
  'Surname': 'Sane',
  'Age': 62,
  'City': 'Hajipur',
  'Hobby': 'Hiking',
  'Bank Name': 'Rout-Sarna Bank',
  'Gender': 'Male'},
 {'First name': 'Bishakha',
  'Surname': 'Roy',
  'Age': 61,
  'City': 'Bathinda',
  'Hobby': 'Hiking',
  'Bank Name': 'Sani, Ramachandran and Pradhan Bank',
  'Gender': 'Female'},
 {'First name': 'Damini',
  'Surname': 'Dube',
  'Age': 52,
  'City': 'Kulti',
  'Hobby': 'Gaming',
  'Bank Name': 'Raval Group Bank',
  'Gender': 'Female'},
 {'First name': 'Wakeeta',
  'Surname': 'Divan',
  'Age': 46,
  'City': 'Bharatpur',
  'Hobby': 'Hiking',
  'Bank Name': 'Jaggi-Natt Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Farhan',
  'Surname': 'Aggarwal',
  'Age': 60,
  'City': 'Mirzapur',
  'Hobby': 'Cooking',
  'Bank Name': 'Gara, Ganesan and Zacharia Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Isaac',
  'Surname': 'Atwal',
  'Age': 41,
  'City': 'Rohtak',
  'Hobby': 'Reading',
  'Bank Name': 'Mannan PLC Bank',
  'Gender': 'Female'},
 {'First name': 'Faraj',
  'Surname': 'Devi',
  'Age': 69,
  'City': 'Burhanpur',
  'Hobby': 'Cooking',
  'Bank Name': 'Vig PLC Bank',
  'Gender': 'Female'},
 {'First name': 'Vasatika',
  'Surname': 'Rajagopal',
  'Age': 61,
  'City': 'Guntakal',
  'Hobby': 'Cooking',
  'Bank Name': 'Kala, Devi and Pillay Bank',
  'Gender': 'Female'},
 {'First name': 'Shivansh',
  'Surname': 'Mahal',
  'Age': 29,
  'City': 'Muzaffarnagar',
  'Hobby': 'Painting',
  'Bank Name': 'Sachdeva-Gandhi Bank',
  'Gender': 'Female'},
 {'First name': 'Advik',
  'Surname': 'Mitra',
  'Age': 45,
  'City': 'Nangloi Jat',
  'Hobby': 'Cooking',
  'Bank Name': 'Shetty, Suri and Lala Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Sudiksha',
  'Surname': 'Arya',
  'Age': 29,
  'City': 'Ramagundam',
  'Hobby': 'Reading',
  'Bank Name': 'Sarraf-Gole Bank',
  'Gender': 'Non-binary'},
 {'First name': 'William',
  'Surname': 'Patil',
  'Age': 56,
  'City': 'Kulti',
  'Hobby': 'Hiking',
  'Bank Name': 'Tailor Inc Bank',
  'Gender': 'Male'},
 {'First name': 'Nicholas',
  'Surname': 'Brar',
  'Age': 69,
  'City': 'Baranagar',
  'Hobby': 'Cycling',
  'Bank Name': 'Bandi, Viswanathan and Raval Bank',
  'Gender': 'Female'},
 {'First name': 'Divya',
  'Surname': 'Patla',
  'Age': 59,
  'City': 'Naihati',
  'Hobby': 'Painting',
  'Bank Name': 'Brahmbhatt Ltd Bank',
  'Gender': 'Female'},
 {'First name': 'Dayita',
  'Surname': 'Narula',
  'Age': 45,
  'City': 'Durg',
  'Hobby': 'Reading',
  'Bank Name': 'Jayaraman, Bali and Atwal Bank',
  'Gender': 'Female'},
 {'First name': 'Dhruv',
  'Surname': 'Sabharwal',
  'Age': 42,
  'City': 'Surat',
  'Hobby': 'Cycling',
  'Bank Name': 'Vohra, Kamdar and Chaudry Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Yamini',
  'Surname': 'Prabhu',
  'Age': 66,
  'City': 'Muzaffarpur',
  'Hobby': 'Painting',
  'Bank Name': 'Sarma PLC Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Jacob',
  'Surname': 'Kibe',
  'Age': 34,
  'City': 'Jaunpur',
  'Hobby': 'Painting',
  'Bank Name': 'Chokshi-Raghavan Bank',
  'Gender': 'Female'},
 {'First name': 'Frado',
  'Surname': 'Upadhyay',
  'Age': 32,
  'City': 'Patiala',
  'Hobby': 'Cycling',
  'Bank Name': 'Kade PLC Bank',
  'Gender': 'Male'},
 {'First name': 'Nakul',
  'Surname': 'Palan',
  'Age': 21,
  'City': 'Chinsurah',
  'Hobby': 'Reading',
  'Bank Name': 'Chatterjee, Vig and Choudhury Bank',
  'Gender': 'Male'},
 {'First name': 'Ranbir',
  'Surname': 'Verma',
  'Age': 38,
  'City': 'Silchar',
  'Hobby': 'Cooking',
  'Bank Name': 'Peri-Deol Bank',
  'Gender': 'Female'},
 {'First name': 'Jeevika',
  'Surname': 'Saini',
  'Age': 68,
  'City': 'Kavali',
  'Hobby': 'Reading',
  'Bank Name': 'Bobal, Mandal and Tak Bank',
  'Gender': 'Male'},
 {'First name': 'Zaid',
  'Surname': 'Radhakrishnan',
  'Age': 51,
  'City': 'Naihati',
  'Hobby': 'Reading',
  'Bank Name': 'Borde Ltd Bank',
  'Gender': 'Male'},
 {'First name': 'Ayush',
  'Surname': 'Pandey',
  'Age': 45,
  'City': 'Pondicherry',
  'Hobby': 'Reading',
  'Bank Name': 'Goyal, Madan and Kakar Bank',
  'Gender': 'Female'},
 {'First name': 'Garima',
  'Surname': 'Pant',
  'Age': 25,
  'City': 'Mau',
  'Hobby': 'Cycling',
  'Bank Name': 'Sharaf PLC Bank',
  'Gender': 'Male'},
 {'First name': 'Adweta',
  'Surname': 'Ravel',
  'Age': 44,
  'City': 'Howrah',
  'Hobby': 'Painting',
  'Bank Name': 'Bali-Behl Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Daksha',
  'Surname': 'Karan',
  'Age': 65,
  'City': 'Baranagar',
  'Hobby': 'Hiking',
  'Bank Name': 'Venkataraman-Ganesan Bank',
  'Gender': 'Female'},
 {'First name': 'Shravya',
  'Surname': 'Dey',
  'Age': 36,
  'City': 'Chittoor',
  'Hobby': 'Reading',
  'Bank Name': 'Mander-Seth Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Chakradev',
  'Surname': 'Misra',
  'Age': 48,
  'City': 'Gaya',
  'Hobby': 'Hiking',
  'Bank Name': 'Dalal-Mitra Bank',
  'Gender': 'Male'},
 {'First name': 'Ekantika',
  'Surname': 'Srinivas',
  'Age': 48,
  'City': 'Hospet',
  'Hobby': 'Reading',
  'Bank Name': 'Viswanathan-Bhavsar Bank',
  'Gender': 'Male'},
 {'First name': 'Ishita',
  'Surname': 'Palla',
  'Age': 35,
  'City': 'South Dumdum',
  'Hobby': 'Cycling',
  'Bank Name': 'Shroff PLC Bank',
  'Gender': 'Female'},
 {'First name': 'Guneet',
  'Surname': 'Chauhan',
  'Age': 34,
  'City': 'Sambhal',
  'Hobby': 'Hiking',
  'Bank Name': 'Mane, Gaba and Sura Bank',
  'Gender': 'Female'},
 {'First name': 'Zilmil',
  'Surname': 'Parmar',
  'Age': 52,
  'City': 'Panvel',
  'Hobby': 'Painting',
  'Bank Name': 'Murthy Group Bank',
  'Gender': 'Male'},
 {'First name': 'Zinal',
  'Surname': 'Sodhi',
  'Age': 25,
  'City': 'Panipat',
  'Hobby': 'Cooking',
  'Bank Name': 'Bumb, Kanda and Prabhakar Bank',
  'Gender': 'Male'},
 {'First name': 'Samar',
  'Surname': 'Kar',
  'Age': 51,
  'City': 'Karawal Nagar',
  'Hobby': 'Cycling',
  'Bank Name': 'Mammen, Butala and Gulati Bank',
  'Gender': 'Male'},
 {'First name': 'Jeevika',
  'Surname': 'Kota',
  'Age': 56,
  'City': 'Madanapalle',
  'Hobby': 'Cycling',
  'Bank Name': 'Hans LLC Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Jacob',
  'Surname': 'Deo',
  'Age': 50,
  'City': 'Thoothukudi',
  'Hobby': 'Gaming',
  'Bank Name': 'Sama Ltd Bank',
  'Gender': 'Male'},
 {'First name': 'Harini',
  'Surname': 'Sant',
  'Age': 20,
  'City': 'Uluberia',
  'Hobby': 'Painting',
  'Bank Name': 'Narayanan-Sood Bank',
  'Gender': 'Male'},
 {'First name': 'Zinal',
  'Surname': 'Behl',
  'Age': 68,
  'City': 'Bareilly',
  'Hobby': 'Gaming',
  'Bank Name': 'Mittal, Raman and Natarajan Bank',
  'Gender': 'Male'},
 {'First name': 'Pushti',
  'Surname': 'Ahluwalia',
  'Age': 24,
  'City': 'Jorhat',
  'Hobby': 'Painting',
  'Bank Name': 'Rout, Kara and Chada Bank',
  'Gender': 'Male'},
 {'First name': 'Tanveer',
  'Surname': 'Lad',
  'Age': 60,
  'City': 'Pali',
  'Hobby': 'Gaming',
  'Bank Name': 'Sachar LLC Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Devansh',
  'Surname': 'Prabhakar',
  'Age': 28,
  'City': 'Tiruppur',
  'Hobby': 'Cooking',
  'Bank Name': 'Chakrabarti, Dalal and Palla Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Faris',
  'Surname': 'Kalita',
  'Age': 32,
  'City': 'Durgapur',
  'Hobby': 'Hiking',
  'Bank Name': 'Krishnamurthy PLC Bank',
  'Gender': 'Female'},
 {'First name': 'Elijah',
  'Surname': 'Gill',
  'Age': 26,
  'City': 'Mira-Bhayandar',
  'Hobby': 'Reading',
  'Bank Name': 'Setty Ltd Bank',
  'Gender': 'Female'},
 {'First name': 'Jagdish',
  'Surname': 'Chaudhary',
  'Age': 34,
  'City': 'Silchar',
  'Hobby': 'Reading',
  'Bank Name': 'Dar, Buch and Bal Bank',
  'Gender': 'Female'},
 {'First name': 'Zaid',
  'Surname': 'Mukherjee',
  'Age': 41,
  'City': 'Udaipur',
  'Hobby': 'Painting',
  'Bank Name': 'Doctor-Bhatia Bank',
  'Gender': 'Male'},
 {'First name': 'Hredhaan',
  'Surname': 'Bera',
  'Age': 67,
  'City': 'Satna',
  'Hobby': 'Cooking',
  'Bank Name': 'Ahuja LLC Bank',
  'Gender': 'Female'},
 {'First name': 'Chandran',
  'Surname': 'Bakshi',
  'Age': 44,
  'City': 'Dewas',
  'Hobby': 'Painting',
  'Bank Name': 'Bora Ltd Bank',
  'Gender': 'Male'},
 {'First name': 'Geetika',
  'Surname': 'Padmanabhan',
  'Age': 30,
  'City': 'Bihar Sharif',
  'Hobby': 'Cycling',
  'Bank Name': 'Majumdar, Ray and Chawla Bank',
  'Gender': 'Male'},
 {'First name': 'Indali',
  'Surname': 'Arya',
  'Age': 25,
  'City': 'Nangloi Jat',
  'Hobby': 'Cooking',
  'Bank Name': 'Chaudhary, Banerjee and Dalal Bank',
  'Gender': 'Male'},
 {'First name': 'Indali',
  'Surname': 'Sundaram',
  'Age': 69,
  'City': 'Singrauli',
  'Hobby': 'Painting',
  'Bank Name': 'Loke-Bhalla Bank',
  'Gender': 'Female'},
 {'First name': 'Wyatt',
  'Surname': 'Dash',
  'Age': 41,
  'City': 'Mathura',
  'Hobby': 'Painting',
  'Bank Name': 'Halder Inc Bank',
  'Gender': 'Female'},
 {'First name': 'Jairaj',
  'Surname': 'Kala',
  'Age': 21,
  'City': 'Mathura',
  'Hobby': 'Gaming',
  'Bank Name': 'Gera-Sarma Bank',
  'Gender': 'Male'},
 {'First name': 'Aradhana',
  'Surname': 'Sheth',
  'Age': 20,
  'City': 'Meerut',
  'Hobby': 'Reading',
  'Bank Name': 'Sarna, Mander and Pingle Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Indrajit',
  'Surname': 'Bansal',
  'Age': 67,
  'City': 'Berhampur',
  'Hobby': 'Painting',
  'Bank Name': 'Ahuja-Parikh Bank',
  'Gender': 'Female'},
 {'First name': 'Radhika',
  'Surname': 'Morar',
  'Age': 37,
  'City': 'Saharsa',
  'Hobby': 'Cooking',
  'Bank Name': 'Randhawa, Misra and Prabhu Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Wridesh',
  'Surname': 'Gara',
  'Age': 24,
  'City': 'Sambalpur',
  'Hobby': 'Reading',
  'Bank Name': 'Joshi, Buch and Talwar Bank',
  'Gender': 'Male'},
 {'First name': 'Panini',
  'Surname': 'Sahni',
  'Age': 45,
  'City': 'Hospet',
  'Hobby': 'Cooking',
  'Bank Name': 'Banik PLC Bank',
  'Gender': 'Male'},
 {'First name': 'Eta',
  'Surname': 'Narayanan',
  'Age': 60,
  'City': 'Kharagpur',
  'Hobby': 'Painting',
  'Bank Name': 'Karpe, Saraf and Nanda Bank',
  'Gender': 'Non-binary'},
 {'First name': 'Zehaan',
  'Surname': 'Dua',
  'Age': 69,
  'City': 'Bokaro',
  'Hobby': 'Gaming',
  'Bank Name': 'Johal Group Bank',
  'Gender': 'Male'},
 {'First name': 'Qabil',
  'Surname': 'Nayar',
  'Age': 18,
  'City': 'Chandigarh',
  'Hobby': 'Hiking',
  'Bank Name': 'Savant, Choudhry and Setty Bank',
  'Gender': 'Female'},
 {'First name': 'Abha',
  'Surname': 'Mohanty',
  'Age': 39,

In [84]:
ds= pd.DataFrame(data)

In [85]:
ds

,First name,Surname,Age,City,Hobby,Bank Name,Gender
0,Advaith,Sunder,25,Bharatpur,Gaming,"Dugar, Shanker and Shanker Bank",Male
1,William,Sinha,54,Gorakhpur,Gaming,Basu PLC Bank,Male
2,Teerth,Tata,65,Kochi,Painting,"Kohli, Kapoor and Patla Bank",Male
3,Raghav,Kata,49,Howrah,Gaming,Nair Inc Bank,Non-binary
4,Azad,Dua,57,Kurnool,Reading,Sahota Group Bank,Male
...,...,...,...,...,...,...,...
995,Patrick,Hegde,51,Darbhanga,Painting,Goel-Naidu Bank,Male
996,Jairaj,Hegde,48,Saharanpur,Gaming,Mitter-Verma Bank,Male
997,Vamakshi,Natarajan,44,Morena,Cooking,Subramanian-Mahal Bank,Female
998,Adya,Swaminathan,57,Tadipatri,Hiking,"Lalla, Gill and Choudhary Bank",Female
999,Aarav,Dar,33,Sambhal,Reading,Minhas Inc Bank,Male

In [86]:
ds.to_csv('PracticeData1.csv', index = False)

In [87]:
df = pd.read_csv('PracticeData1.csv')

In [88]:
df

,First name,Surname,Age,City,Hobby,Bank Name,Gender
0,Advaith,Sunder,25,Bharatpur,Gaming,"Dugar, Shanker and Shanker Bank",Male
1,William,Sinha,54,Gorakhpur,Gaming,Basu PLC Bank,Male
2,Teerth,Tata,65,Kochi,Painting,"Kohli, Kapoor and Patla Bank",Male
3,Raghav,Kata,49,Howrah,Gaming,Nair Inc Bank,Non-binary
4,Azad,Dua,57,Kurnool,Reading,Sahota Group Bank,Male
...,...,...,...,...,...,...,...
995,Patrick,Hegde,51,Darbhanga,Painting,Goel-Naidu Bank,Male
996,Jairaj,Hegde,48,Saharanpur,Gaming,Mitter-Verma Bank,Male
997,Vamakshi,Natarajan,44,Morena,Cooking,Subramanian-Mahal Bank,Female
998,Adya,Swaminathan,57,Tadipatri,Hiking,"Lalla, Gill and Choudhary Bank",Female
999,Aarav,Dar,33,Sambhal,Reading,Minhas Inc Bank,Male

In [89]:
df.sort_values(by = 'Surname')

,First name,Surname,Age,City,Hobby,Bank Name,Gender
143,Shravya,Acharya,65,Kochi,Cooking,Suri Group Bank,Non-binary
993,Chanchal,Agate,41,Patiala,Painting,"Khare, Ramakrishnan and Bakshi Bank",Male
597,Anika,Aggarwal,68,Jammu,Gaming,Batra and Sons Bank,Male
61,Farhan,Aggarwal,60,Mirzapur,Cooking,"Gara, Ganesan and Zacharia Bank",Non-binary
478,Warhi,Aggarwal,63,Shimla,Gaming,Kadakia and Sons Bank,Non-binary
...,...,...,...,...,...,...,...
353,Ishani,Yogi,42,Vellore,Reading,"Wason, Parikh and Brar Bank",Female
912,Chasmum,Yogi,37,Rewa,Painting,Chaudhry-Mand Bank,Female
948,Ishanvi,Yohannan,64,Khammam,Reading,Cheema-Chakraborty Bank,Non-binary
348,Ijaya,Yohannan,45,Sangli-Miraj & Kupwad,Reading,Murty-Deol Bank,Male
382,Matthew,Yohannan,61,Jaipur,Gaming,Mukherjee Group Bank,Male

In [90]:
df.sort_values(by = ['Surname', 'City'])

,First name,Surname,Age,City,Hobby,Bank Name,Gender
143,Shravya,Acharya,65,Kochi,Cooking,Suri Group Bank,Non-binary
993,Chanchal,Agate,41,Patiala,Painting,"Khare, Ramakrishnan and Bakshi Bank",Male
597,Anika,Aggarwal,68,Jammu,Gaming,Batra and Sons Bank,Male
646,Nirja,Aggarwal,37,Mahbubnagar,Hiking,"Chada, Dhillon and Mand Bank",Female
61,Farhan,Aggarwal,60,Mirzapur,Cooking,"Gara, Ganesan and Zacharia Bank",Non-binary
...,...,...,...,...,...,...,...
328,Zashil,Yogi,42,Shimla,Cooking,Nayar LLC Bank,Female
353,Ishani,Yogi,42,Vellore,Reading,"Wason, Parikh and Brar Bank",Female
382,Matthew,Yohannan,61,Jaipur,Gaming,Mukherjee Group Bank,Male
948,Ishanvi,Yohannan,64,Khammam,Reading,Cheema-Chakraborty Bank,Non-binary
348,Ijaya,Yohannan,45,Sangli-Miraj & Kupwad,Reading,Murty-Deol Bank,Male

In [91]:
ds['Age'].nlargest(3)

34     70
196    70
406    70
Name: Age, dtype: int64

In [92]:
ds.groupby('Gender')['Age'].mean()

Gender
Female        43.620000
Male          42.991018
Non-binary    42.433544
Name: Age, dtype: float64

In [93]:
ds.groupby('City')['First name'].count()

City
Adoni            2
Agartala         3
Agra             4
Ahmedabad        3
Aizawl           4
                ..
Vijayanagaram    5
Vijayawada       5
Visakhapatnam    2
Warangal         3
Yamunanagar      4
Name: First name, Length: 299, dtype: int64

In [94]:
ds.groupby('Bank Name')['Age'].count()

Bank Name
Agarwal, Din and Iyer Bank              1
Agate and Sons Bank                     1
Aggarwal Inc Bank                       1
Ahluwalia, Aurora and Nagarajan Bank    1
Ahluwalia, Sharaf and Thaman Bank       1
                                       ..
Zacharia, Dar and Khanna Bank           1
Zacharia, Mitra and Arora Bank          1
Zacharia, Oak and Palan Bank            1
Zachariah-Edwin Bank                    1
Zachariah-Mangal Bank                   1
Name: Age, Length: 993, dtype: int64

In [95]:
ds.groupby(['Gender','Hobby'])['Age'].count()

Gender      Hobby
Female      Cooking     63
            Cycling     58
            Gaming      62
            Hiking      51
            Painting    58
            Reading     58
Male        Cooking     57
            Cycling     55
            Gaming      55
            Hiking      54
            Painting    51
            Reading     62
Non-binary  Cooking     52
            Cycling     57
            Gaming      55
            Hiking      57
            Painting    53
            Reading     42
Name: Age, dtype: int64

In [96]:
ds.groupby('Gender')['Age'].sum()

Gender
Female        15267
Male          14359
Non-binary    13409
Name: Age, dtype: int64

In [97]:
ds.groupby('Gender')['Age'].max()

Gender
Female        70
Male          70
Non-binary    70
Name: Age, dtype: int64

In [103]:
ds.groupby('Gender').agg(
    {
    'Age': ['mean', 'sum'],
    'Hobby': 'count',
    'Bank Name': 'nunique'
    }
)

                  Age        Hobby Bank Name
                 mean    sum count   nunique
Gender
Female      43.620000  15267   350       350
Male        42.991018  14359   334       334
Non-binary  42.433544  13409   316       314

In [108]:
filt = ds['City'] != 'Jaipur'
ds.loc[filt]['Hobby'].value_counts()

Hobby
Cooking     171
Gaming      170
Cycling     167
Painting    162
Reading     162
Hiking      160
Name: count, dtype: int64

In [107]:
filt = ds['City'] == 'Jaipur'
ds.loc[filt]['Hobby'].value_counts()

Hobby
Cycling    3
Hiking     2
Gaming     2
Cooking    1
Name: count, dtype: int64

In [109]:
filt = ds['Age'] < 24
ds.loc[filt]['City'].str.contains('Jaipur').sum()

np.int64(1)

In [102]:
ds.loc[4]

First name                 Azad
Surname                     Dua
Age                          57
City                    Kurnool
Hobby                   Reading
Bank Name     Sahota Group Bank
Gender                     Male
Name: 4, dtype: object